import { IconName } from "@reearth/app/lib/reearth-ui";

export enum PlateauDatasetType {
  Area = "area",
  Border = "border",
  Bridge = "brid",
  Building = "bldg",
  CityFurniture = "frn",
  EmergencyRoute = "emergency_route",
  Global = "global",
  GenericCityObject = "gen",
  HighTideRisk = "htd",
  InlandFloodingRisk = "ifld",
  ReservoirFloodingRisk = "rfld",
  LandSlideRisk = "lsld",
  LandUse = "luse",
  Landmark = "landmark",
  Park = "park",
  Railway = "railway",
  RiverFloodingRisk = "fld",
  Road = "tran",
  Shelter = "shelter",
  Station = "station",
  TsunamiRisk = "tnm",
  UrbanPlanning = "urf",
  UseCase = "usecase",
  Vegetation = "veg",
  Sample = "sample",
  City = "city",
  Constructure = "cons",
  Water = "wtr",
  Traffic = "trk",
  WaterWay = "wwy"
}

export const datasetTypeIcons: Record<PlateauDatasetType, IconName> = {
  [PlateauDatasetType.Area]: "plateauUseCase",
  [PlateauDatasetType.Border]: "plateauBorder",
  [PlateauDatasetType.Bridge]: "plateauBridge",
  [PlateauDatasetType.Building]: "plateauBuilding",
  [PlateauDatasetType.EmergencyRoute]: "plateauEmergencyRoute",
  [PlateauDatasetType.UrbanPlanning]: "plateauUrbanPlanning",
  [PlateauDatasetType.RiverFloodingRisk]: "plateauRiverFloodingRisk",
  [PlateauDatasetType.CityFurniture]: "plateauCityFurniture",
  [PlateauDatasetType.GenericCityObject]: "plateauGenericCityObject",
  [PlateauDatasetType.Global]: "plateauUseCase",
  [PlateauDatasetType.HighTideRisk]: "plateauHighTideRisk",
  [PlateauDatasetType.InlandFloodingRisk]: "plateauInlandFloodingRisk",
  [PlateauDatasetType.ReservoirFloodingRisk]: "plateauReservoirFloodingRisk",
  [PlateauDatasetType.Landmark]: "plateauLandmark",
  [PlateauDatasetType.LandSlideRisk]: "plateauLandSlideRisk",
  [PlateauDatasetType.LandUse]: "plateauLandUse",
  [PlateauDatasetType.Park]: "plateauPark",
  [PlateauDatasetType.Railway]: "plateauRailway",
  [PlateauDatasetType.Road]: "plateauRoad",
  [PlateauDatasetType.Shelter]: "plateauShelter",
  [PlateauDatasetType.Station]: "plateauStation",
  [PlateauDatasetType.TsunamiRisk]: "plateauTsunamiRisk",
  [PlateauDatasetType.UseCase]: "plateauUseCase",
  [PlateauDatasetType.Vegetation]: "plateauVegetation",
  [PlateauDatasetType.Sample]: "plateauUseCase",
  [PlateauDatasetType.City]: "plateauUseCase",
  [PlateauDatasetType.Constructure]: "plateauUseCase",
  [PlateauDatasetType.Water]: "plateauUseCase",
  [PlateauDatasetType.WaterWay]: "plateauUseCase",
  [PlateauDatasetType.Traffic]: "plateauUseCase"
} as const;

export const TOKYO_CODE = "13";
