package manifest

// generated by "/var/folders/sd/pfjp2mqd1cs6hd_vj09vjnl00000gn/T/go-build1416482179/b001/exe/schematyper -o pkg/plugin/manifest/schema_translation.go --package manifest --prefix Translation ./schemas/plugin_manifest_translation.json" -- DO NOT EDIT

type TranslationChoice string

type TranslationExtension struct {
	Description    *string                   `json:"description,omitempty"`
	Name           *string                   `json:"name,omitempty"`
	PropertySchema TranslationPropertySchema `json:"propertySchema,omitempty"`
}

type TranslationPropertySchema map[string]TranslationPropertySchemaGroup

type TranslationPropertySchemaField struct {
	Choices     map[string]TranslationChoice `json:"choices,omitempty"`
	Description *string                      `json:"description,omitempty"`
	Placeholder *string                      `json:"placeholder,omitempty"`
	Prefix      *string                      `json:"prefix,omitempty"`
	Suffix      *string                      `json:"suffix,omitempty"`
	Title       *string                      `json:"title,omitempty"`
}

type TranslationPropertySchemaGroup struct {
	Description *string                                   `json:"description,omitempty"`
	Fields      map[string]TranslationPropertySchemaField `json:"fields,omitempty"`
	Title       *string                                   `json:"title,omitempty"`
}

type TranslationRoot struct {
	Description *string                         `json:"description,omitempty"`
	Extensions  map[string]TranslationExtension `json:"extensions,omitempty"`
	Name        *string                         `json:"name,omitempty"`
	Schema      TranslationPropertySchema       `json:"schema,omitempty"`
}
