#!/usr/bin/env node
/**
 * build-plugin.js
 *
 * Reads *-test.js fragment files and combines them into reearth-api-test.js —
 * the single widget served by the E2E fixture plugin.
 *
 * Usage:
 *   node build-plugin.js              # combine ALL fragments
 *   node build-plugin.js camera       # combine only camera-test.js
 *   node build-plugin.js camera layers  # combine camera-test.js + layers-test.js
 *
 * After running, rebuild the zip:
 *   zip -j ../reearth-api-test.zip reearth.yml reearth-api-test.js
 *
 * Fragment contract:
 *   exports.html      {string}    HTML markup + inline <script> click handlers
 *   exports.onMessage {function}  Handler for reearth.extension.on("message").
 *                                 May reference the global `reearth` object —
 *                                 it runs in the plugin context, not in Node.
 */

const fs = require("fs");
const path = require("path");

const dir = __dirname;

// CLI args: optional list of fragment prefixes (without "-test.js")
// e.g. node build-plugin.js camera layers  →  camera-test.js, layers-test.js
const requested = process.argv.slice(2);

let fragmentFiles;
if (requested.length > 0) {
  fragmentFiles = requested.map(name => {
    const file = name.endsWith("-test.js") ? name : `${name}-test.js`;
    if (!fs.existsSync(path.join(dir, file))) {
      console.error(`[build-plugin] Fragment not found: ${file}`);
      process.exit(1);
    }
    return file;
  });
} else {
  fragmentFiles = fs
    .readdirSync(dir)
    .filter(f => f.endsWith("-test.js"))
    .sort();
}

if (fragmentFiles.length === 0) {
  console.error("[build-plugin] No *-test.js fragment files found in", dir);
  process.exit(1);
}

const fragments = fragmentFiles.map(f => {
  const mod = require(path.join(dir, f));
  if (typeof mod.html !== "string" || typeof mod.onMessage !== "function") {
    console.error(
      `[build-plugin] ${f} must export { html: string, onMessage: function }`
    );
    process.exit(1);
  }
  return { name: f, html: mod.html, onMessage: mod.onMessage };
});

function extractBody(fn) {
  const src = fn.toString();
  const start = src.indexOf("{") + 1;
  const end = src.lastIndexOf("}");
  return src.slice(start, end).trim();
}

const combinedHtml = fragments
  .map(f => `  <!-- ${f.name} -->\n${f.html.trim()}`)
  .join("\n\n");

const handlerParts = fragments
  .map(f => `  // ── ${f.name} ──\n  ${extractBody(f.onMessage)}`)
  .join("\n\n");

const output = `// AUTO-GENERATED by build-plugin.js — do not edit directly.
// Sources: ${fragmentFiles.join(", ")}
// To update: edit a *-test.js fragment, then run:
//   node build-plugin.js
//   zip -j ../reearth-api-test.zip reearth.yml reearth-api-test.js

reearth.ui.show(\`
${combinedHtml}
\`);

reearth.extension.on("message", function(msg) {
${handlerParts}
});
`;

const outPath = path.join(dir, "reearth-api-test.js");
fs.writeFileSync(outPath, output, "utf-8");
console.log(`[build-plugin] Generated: ${outPath}`);
console.log(`[build-plugin] Sources:   ${fragmentFiles.join(", ")}`);
