// Code generated by gen, DO NOT EDIT.

package dataloader

import (
	"context"
	"time"

	"github.com/reearth/reearth-backend/internal/adapter/graphql"
	"github.com/reearth/reearth-backend/internal/usecase"
	"github.com/reearth/reearth-backend/pkg/id"
)

type LayerGroupDataLoader interface {
	Load(id.LayerID) (*graphql.LayerGroup, error)
	LoadAll([]id.LayerID) ([]*graphql.LayerGroup, []error)
}

func newLayerGroup(ctx context.Context, c *graphql.LayerController, o *usecase.Operator) *LayerGroupLoader {
	return NewLayerGroupLoader(LayerGroupLoaderConfig{
		Wait:     1 * time.Millisecond,
		MaxBatch: 100,
		Fetch: func(keys []id.LayerID) ([]*graphql.LayerGroup, []error) {
			return c.FetchGroup(ctx, keys, o)
		},
	})
}

func newOrdinaryLayerGroup(ctx context.Context, c *graphql.LayerController, o *usecase.Operator) LayerGroupDataLoader {
	return &ordinaryLayerGroupLoader{
		fetch: func(keys []id.LayerID) ([]*graphql.LayerGroup, []error) {
			return c.FetchGroup(ctx, keys, o)
		},
	}
}

type ordinaryLayerGroupLoader struct {
	fetch func(keys []id.LayerID) ([]*graphql.LayerGroup, []error)
}

func (l *ordinaryLayerGroupLoader) Load(key id.LayerID) (*graphql.LayerGroup, error) {
	res, errs := l.fetch([]id.LayerID{key})
	if len(errs) > 0 {
		return nil, errs[0]
	}
	if len(res) > 0 {
		return res[0], nil
	}
	return nil, nil
}

func (l *ordinaryLayerGroupLoader) LoadAll(keys []id.LayerID) ([]*graphql.LayerGroup, []error) {
	return l.fetch(keys)
}
