// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

	"github.com/reearth/reearth-backend/internal/adapter/graphql"
	"github.com/reearth/reearth-backend/pkg/id"
)

// PropertySchemaLoaderConfig captures the config to create a new PropertySchemaLoader
type PropertySchemaLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []id.PropertySchemaID) ([]*graphql.PropertySchema, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewPropertySchemaLoader creates a new PropertySchemaLoader given a fetch, wait, and maxBatch
func NewPropertySchemaLoader(config PropertySchemaLoaderConfig) *PropertySchemaLoader {
	return &PropertySchemaLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// PropertySchemaLoader batches and caches requests
type PropertySchemaLoader struct {
	// this method provides the data for the loader
	fetch func(keys []id.PropertySchemaID) ([]*graphql.PropertySchema, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[id.PropertySchemaID]*graphql.PropertySchema

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *propertySchemaLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type propertySchemaLoaderBatch struct {
	keys    []id.PropertySchemaID
	data    []*graphql.PropertySchema
	error   []error
	closing bool
	done    chan struct{}
}

// Load a PropertySchema by key, batching and caching will be applied automatically
func (l *PropertySchemaLoader) Load(key id.PropertySchemaID) (*graphql.PropertySchema, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a PropertySchema.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PropertySchemaLoader) LoadThunk(key id.PropertySchemaID) func() (*graphql.PropertySchema, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (*graphql.PropertySchema, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &propertySchemaLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (*graphql.PropertySchema, error) {
		<-batch.done

		var data *graphql.PropertySchema
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *PropertySchemaLoader) LoadAll(keys []id.PropertySchemaID) ([]*graphql.PropertySchema, []error) {
	results := make([]func() (*graphql.PropertySchema, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	propertySchemas := make([]*graphql.PropertySchema, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		propertySchemas[i], errors[i] = thunk()
	}
	return propertySchemas, errors
}

// LoadAllThunk returns a function that when called will block waiting for a PropertySchemas.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PropertySchemaLoader) LoadAllThunk(keys []id.PropertySchemaID) func() ([]*graphql.PropertySchema, []error) {
	results := make([]func() (*graphql.PropertySchema, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]*graphql.PropertySchema, []error) {
		propertySchemas := make([]*graphql.PropertySchema, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			propertySchemas[i], errors[i] = thunk()
		}
		return propertySchemas, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *PropertySchemaLoader) Prime(key id.PropertySchemaID, value *graphql.PropertySchema) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := *value
		l.unsafeSet(key, &cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *PropertySchemaLoader) Clear(key id.PropertySchemaID) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *PropertySchemaLoader) unsafeSet(key id.PropertySchemaID, value *graphql.PropertySchema) {
	if l.cache == nil {
		l.cache = map[id.PropertySchemaID]*graphql.PropertySchema{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *propertySchemaLoaderBatch) keyIndex(l *PropertySchemaLoader, key id.PropertySchemaID) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *propertySchemaLoaderBatch) startTimer(l *PropertySchemaLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *propertySchemaLoaderBatch) end(l *PropertySchemaLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
