// Code generated by go generate; DO NOT EDIT.
package locales

const (
	ErrKeyUnknown ErrorKey = "unknown"
	ErrKeyRepoNotFound ErrorKey = "repo.not_found"
	ErrKeyPkgProjectInvalidAlias ErrorKey = "pkg.project.invalid_alias"
)
