// Code generated by gen, DO NOT EDIT.

package id

import (
	"encoding/json"
	"errors"
	"testing"

	"github.com/oklog/ulid"
	"github.com/stretchr/testify/assert"
)

func TestNewInfoboxFieldID(t *testing.T) {
	id := NewInfoboxFieldID()
	assert.NotNil(t, id)
	ulID, err := ulid.Parse(id.String())

	assert.NotNil(t, ulID)
	assert.Nil(t, err)
}

func TestInfoboxFieldIDFrom(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    string
		expected struct {
			result InfoboxFieldID
			err    error
		}
	}{
		{
			name:  "Fail:Not valid string",
			input: "testMustFail",
			expected: struct {
				result InfoboxFieldID
				err    error
			}{
				InfoboxFieldID{},
				ErrInvalidID,
			},
		},
		{
			name:  "Fail:Not valid string",
			input: "",
			expected: struct {
				result InfoboxFieldID
				err    error
			}{
				InfoboxFieldID{},
				ErrInvalidID,
			},
		},
		{
			name:  "success:valid string",
			input: "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: struct {
				result InfoboxFieldID
				err    error
			}{
				InfoboxFieldID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
				nil,
			},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			result, err := InfoboxFieldIDFrom(tc.input)
			assert.Equal(tt, tc.expected.result, result)
			if err != nil {
				assert.True(tt, errors.As(tc.expected.err, &err))
			}
		})
	}
}

func TestMustInfoboxFieldID(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name        string
		input       string
		shouldPanic bool
		expected    InfoboxFieldID
	}{
		{
			name:        "Fail:Not valid string",
			input:       "testMustFail",
			shouldPanic: true,
		},
		{
			name:        "Fail:Not valid string",
			input:       "",
			shouldPanic: true,
		},
		{
			name:        "success:valid string",
			input:       "01f2r7kg1fvvffp0gmexgy5hxy",
			shouldPanic: false,
			expected:    InfoboxFieldID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			if tc.shouldPanic {
				assert.Panics(tt, func() { MustBeID(tc.input) })
				return
			}
			result := MustInfoboxFieldID(tc.input)
			assert.Equal(tt, tc.expected, result)
		})
	}
}

func TestInfoboxFieldIDFromRef(t *testing.T) {
	testCases := []struct {
		name     string
		input    string
		expected *InfoboxFieldID
	}{
		{
			name:     "Fail:Not valid string",
			input:    "testMustFail",
			expected: nil,
		},
		{
			name:     "Fail:Not valid string",
			input:    "",
			expected: nil,
		},
		{
			name:     "success:valid string",
			input:    "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: &InfoboxFieldID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			result := InfoboxFieldIDFromRef(&tc.input)
			assert.Equal(tt, tc.expected, result)
			if tc.expected != nil {
				assert.Equal(tt, *tc.expected, *result)
			}
		})
	}
}

func TestInfoboxFieldIDFromRefID(t *testing.T) {
	id := New()

	subId := InfoboxFieldIDFromRefID(&id)

	assert.NotNil(t, subId)
	assert.Equal(t, subId.id, id.id)
}

func TestInfoboxFieldID_ID(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	idOrg := subId.ID()

	assert.Equal(t, id, idOrg)
}

func TestInfoboxFieldID_String(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	assert.Equal(t, subId.String(), id.String())
}

func TestInfoboxFieldID_GoString(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	assert.Equal(t, subId.GoString(), "id.InfoboxFieldID("+id.String()+")")
}

func TestInfoboxFieldID_RefString(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	refString := subId.StringRef()

	assert.NotNil(t, refString)
	assert.Equal(t, *refString, id.String())
}

func TestInfoboxFieldID_Ref(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	subIdRef := subId.Ref()

	assert.Equal(t, *subId, *subIdRef)
}

func TestInfoboxFieldID_Contains(t *testing.T) {
	id := NewInfoboxFieldID()
	id2 := NewInfoboxFieldID()
	assert.True(t, id.Contains([]InfoboxFieldID{id, id2}))
	assert.False(t, id.Contains([]InfoboxFieldID{id2}))
}

func TestInfoboxFieldID_CopyRef(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	subIdCopyRef := subId.CopyRef()

	assert.Equal(t, *subId, *subIdCopyRef)
	assert.NotSame(t, subId, subIdCopyRef)
}

func TestInfoboxFieldID_IDRef(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	assert.Equal(t, id, *subId.IDRef())
}

func TestInfoboxFieldID_StringRef(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	assert.Equal(t, *subId.StringRef(), id.String())
}

func TestInfoboxFieldID_MarhsalJSON(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	res, err := subId.MarhsalJSON()
	exp, _ := json.Marshal(subId.String())

	assert.Nil(t, err)
	assert.Equal(t, exp, res)
}

func TestInfoboxFieldID_UnmarhsalJSON(t *testing.T) {
	jsonString := "\"01f3zhkysvcxsnzepyyqtq21fb\""

	subId := &InfoboxFieldID{}

	err := subId.UnmarhsalJSON([]byte(jsonString))

	assert.Nil(t, err)
	assert.Equal(t, "01f3zhkysvcxsnzepyyqtq21fb", subId.String())
}

func TestInfoboxFieldID_MarshalText(t *testing.T) {
	id := New()
	subId := InfoboxFieldIDFromRefID(&id)

	res, err := subId.MarshalText()

	assert.Nil(t, err)
	assert.Equal(t, []byte(id.String()), res)
}

func TestInfoboxFieldID_UnmarshalText(t *testing.T) {
	text := []byte("01f3zhcaq35403zdjnd6dcm0t2")

	subId := &InfoboxFieldID{}

	err := subId.UnmarshalText(text)

	assert.Nil(t, err)
	assert.Equal(t, "01f3zhcaq35403zdjnd6dcm0t2", subId.String())

}

func TestInfoboxFieldID_IsNil(t *testing.T) {
	subId := InfoboxFieldID{}

	assert.True(t, subId.IsNil())

	id := New()
	subId = *InfoboxFieldIDFromRefID(&id)

	assert.False(t, subId.IsNil())
}

func TestInfoboxFieldIDToKeys(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []InfoboxFieldID
		expected []string
	}{
		{
			name:     "Empty slice",
			input:    make([]InfoboxFieldID, 0),
			expected: make([]string, 0),
		},
		{
			name:     "1 element",
			input:    []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
		},
		{
			name: "multiple elements",
			input: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			assert.Equal(tt, tc.expected, InfoboxFieldIDToKeys(tc.input))
		})
	}

}

func TestInfoboxFieldIDsFrom(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []string
		expected struct {
			res []InfoboxFieldID
			err error
		}
	}{
		{
			name:  "Empty slice",
			input: make([]string, 0),
			expected: struct {
				res []InfoboxFieldID
				err error
			}{
				res: make([]InfoboxFieldID, 0),
				err: nil,
			},
		},
		{
			name:  "1 element",
			input: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
			expected: struct {
				res []InfoboxFieldID
				err error
			}{
				res: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []InfoboxFieldID
				err error
			}{
				res: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []InfoboxFieldID
				err error
			}{
				res: nil,
				err: ErrInvalidID,
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			if tc.expected.err != nil {
				_, err := InfoboxFieldIDsFrom(tc.input)
				assert.True(tt, errors.As(ErrInvalidID, &err))
			} else {
				res, err := InfoboxFieldIDsFrom(tc.input)
				assert.Equal(tt, tc.expected.res, res)
				assert.Nil(tt, err)
			}

		})
	}
}

func TestInfoboxFieldIDsFromID(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []ID
		expected []InfoboxFieldID
	}{
		{
			name:     "Empty slice",
			input:    make([]ID, 0),
			expected: make([]InfoboxFieldID, 0),
		},
		{
			name:     "1 element",
			input:    []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := InfoboxFieldIDsFromID(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestInfoboxFieldIDsFromIDRef(t *testing.T) {
	t.Parallel()

	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")

	testCases := []struct {
		name     string
		input    []*ID
		expected []InfoboxFieldID
	}{
		{
			name:     "Empty slice",
			input:    make([]*ID, 0),
			expected: make([]InfoboxFieldID, 0),
		},
		{
			name:     "1 element",
			input:    []*ID{&id1},
			expected: []InfoboxFieldID{MustInfoboxFieldID(id1.String())},
		},
		{
			name:  "multiple elements",
			input: []*ID{&id1, &id2, &id3},
			expected: []InfoboxFieldID{
				MustInfoboxFieldID(id1.String()),
				MustInfoboxFieldID(id2.String()),
				MustInfoboxFieldID(id3.String()),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := InfoboxFieldIDsFromIDRef(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestInfoboxFieldIDsToID(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    []InfoboxFieldID
		expected []ID
	}{
		{
			name:     "Empty slice",
			input:    make([]InfoboxFieldID, 0),
			expected: make([]ID, 0),
		},
		{
			name:     "1 element",
			input:    []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := InfoboxFieldIDsToID(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestInfoboxFieldIDsToIDRef(t *testing.T) {
	t.Parallel()

	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	subId1 := MustInfoboxFieldID(id1.String())
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	subId2 := MustInfoboxFieldID(id2.String())
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")
	subId3 := MustInfoboxFieldID(id3.String())

	testCases := []struct {
		name     string
		input    []*InfoboxFieldID
		expected []*ID
	}{
		{
			name:     "Empty slice",
			input:    make([]*InfoboxFieldID, 0),
			expected: make([]*ID, 0),
		},
		{
			name:     "1 element",
			input:    []*InfoboxFieldID{&subId1},
			expected: []*ID{&id1},
		},
		{
			name:     "multiple elements",
			input:    []*InfoboxFieldID{&subId1, &subId2, &subId3},
			expected: []*ID{&id1, &id2, &id3},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := InfoboxFieldIDsToIDRef(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestNewInfoboxFieldIDSet(t *testing.T) {
	InfoboxFieldIdSet := NewInfoboxFieldIDSet()

	assert.NotNil(t, InfoboxFieldIdSet)
	assert.Empty(t, InfoboxFieldIdSet.m)
	assert.Empty(t, InfoboxFieldIdSet.s)
}

func TestInfoboxFieldIDSet_Add(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    []InfoboxFieldID
		expected *InfoboxFieldIDSet
	}{
		{
			name:  "Empty slice",
			input: make([]InfoboxFieldID, 0),
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{},
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
		{
			name: "multiple elements with duplication",
			input: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			set := NewInfoboxFieldIDSet()
			set.Add(tc.input...)
			assert.Equal(tt, tc.expected, set)
		})
	}
}

func TestInfoboxFieldIDSet_AddRef(t *testing.T) {
	t.Parallel()

	InfoboxFieldId := MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")

	testCases := []struct {
		name     string
		input    *InfoboxFieldID
		expected *InfoboxFieldIDSet
	}{
		{
			name:  "Empty slice",
			input: nil,
			expected: &InfoboxFieldIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: &InfoboxFieldId,
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			set := NewInfoboxFieldIDSet()
			set.AddRef(tc.input)
			assert.Equal(tt, tc.expected, set)
		})
	}
}

func TestInfoboxFieldIDSet_Has(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name  string
		input struct {
			InfoboxFieldIDSet
			InfoboxFieldID
		}
		expected bool
	}{
		{
			name: "Empty Set",
			input: struct {
				InfoboxFieldIDSet
				InfoboxFieldID
			}{InfoboxFieldIDSet: InfoboxFieldIDSet{}, InfoboxFieldID: MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: false,
		},
		{
			name: "Set Contains the element",
			input: struct {
				InfoboxFieldIDSet
				InfoboxFieldID
			}{InfoboxFieldIDSet: InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			}, InfoboxFieldID: MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: true,
		},
		{
			name: "Set does not Contains the element",
			input: struct {
				InfoboxFieldIDSet
				InfoboxFieldID
			}{InfoboxFieldIDSet: InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			}, InfoboxFieldID: MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: false,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			assert.Equal(tt, tc.expected, tc.input.InfoboxFieldIDSet.Has(tc.input.InfoboxFieldID))
		})
	}
}

func TestInfoboxFieldIDSet_Clear(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    InfoboxFieldIDSet
		expected InfoboxFieldIDSet
	}{
		{
			name:  "Empty Set",
			input: InfoboxFieldIDSet{},
			expected: InfoboxFieldIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name: "Set Contains the element",
			input: InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: InfoboxFieldIDSet{
				m: nil,
				s: nil,
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			set := tc.input
			p := &set
			p.Clear()
			assert.Equal(tt, tc.expected, *p)
		})
	}
}

func TestInfoboxFieldIDSet_All(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    *InfoboxFieldIDSet
		expected []InfoboxFieldID
	}{
		{
			name: "Empty slice",
			input: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{},
				s: nil,
			},
			expected: make([]InfoboxFieldID, 0),
		},
		{
			name: "1 element",
			input: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
		},
		{
			name: "multiple elements",
			input: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: []InfoboxFieldID{
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			assert.Equal(tt, tc.expected, tc.input.All())
		})
	}
}

func TestInfoboxFieldIDSet_Clone(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    *InfoboxFieldIDSet
		expected *InfoboxFieldIDSet
	}{
		{
			name:     "nil set",
			input:    nil,
			expected: NewInfoboxFieldIDSet(),
		},
		{
			name:     "Empty set",
			input:    NewInfoboxFieldIDSet(),
			expected: NewInfoboxFieldIDSet(),
		},
		{
			name: "1 element",
			input: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			clone := tc.input.Clone()
			assert.Equal(tt, tc.expected, clone)
			assert.False(tt, tc.input == clone)
		})
	}
}

func TestInfoboxFieldIDSet_Merge(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name  string
		input struct {
			a *InfoboxFieldIDSet
			b *InfoboxFieldIDSet
		}
		expected *InfoboxFieldIDSet
	}{
		{
			name: "Empty Set",
			input: struct {
				a *InfoboxFieldIDSet
				b *InfoboxFieldIDSet
			}{
				a: &InfoboxFieldIDSet{},
				b: &InfoboxFieldIDSet{},
			},
			expected: &InfoboxFieldIDSet{},
		},
		{
			name: "1 Empty Set",
			input: struct {
				a *InfoboxFieldIDSet
				b *InfoboxFieldIDSet
			}{
				a: &InfoboxFieldIDSet{
					m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &InfoboxFieldIDSet{},
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "2 non Empty Set",
			input: struct {
				a *InfoboxFieldIDSet
				b *InfoboxFieldIDSet
			}{
				a: &InfoboxFieldIDSet{
					m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &InfoboxFieldIDSet{
					m: map[InfoboxFieldID]struct{}{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {}},
					s: []InfoboxFieldID{MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2")},
				},
			},
			expected: &InfoboxFieldIDSet{
				m: map[InfoboxFieldID]struct{}{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"): {},
				},
				s: []InfoboxFieldID{
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustInfoboxFieldID("01f3zhcaq35403zdjnd6dcm0t2"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			assert.Equal(tt, tc.expected, tc.input.a.Merge(tc.input.b))
		})
	}
}
