// Code generated by gen, DO NOT EDIT.

package id

import "encoding/json"

// PropertyItemID is an ID for PropertyItem.
type PropertyItemID ID

// NewPropertyItemID generates a new PropertyItemId.
func NewPropertyItemID() PropertyItemID {
	return PropertyItemID(New())
}

// PropertyItemIDFrom generates a new PropertyItemID from a string.
func PropertyItemIDFrom(i string) (nid PropertyItemID, err error) {
	var did ID
	did, err = FromID(i)
	if err != nil {
		return
	}
	nid = PropertyItemID(did)
	return
}

// MustPropertyItemID generates a new PropertyItemID from a string, but panics if the string cannot be parsed.
func MustPropertyItemID(i string) PropertyItemID {
	did, err := FromID(i)
	if err != nil {
		panic(err)
	}
	return PropertyItemID(did)
}

// PropertyItemIDFromRef generates a new PropertyItemID from a string ref.
func PropertyItemIDFromRef(i *string) *PropertyItemID {
	did := FromIDRef(i)
	if did == nil {
		return nil
	}
	nid := PropertyItemID(*did)
	return &nid
}

// PropertyItemIDFromRefID generates a new PropertyItemID from a ref of a generic ID.
func PropertyItemIDFromRefID(i *ID) *PropertyItemID {
	if i == nil || i.IsNil() {
		return nil
	}
	nid := PropertyItemID(*i)
	return &nid
}

// ID returns a domain ID.
func (d PropertyItemID) ID() ID {
	return ID(d)
}

// String returns a string representation.
func (d PropertyItemID) String() string {
	if d.IsNil() {
		return ""
	}
	return ID(d).String()
}

// StringRef returns a reference of the string representation.
func (d PropertyItemID) RefString() *string {
	if d.IsNil() {
		return nil
	}
	str := d.String()
	return &str
}

// GoString implements fmt.GoStringer interface.
func (d PropertyItemID) GoString() string {
	return "PropertyItemID(" + d.String() + ")"
}

// Ref returns a reference.
func (d PropertyItemID) Ref() *PropertyItemID {
	if d.IsNil() {
		return nil
	}
	d2 := d
	return &d2
}

// Contains returns whether the id is contained in the slice.
func (d PropertyItemID) Contains(ids []PropertyItemID) bool {
	if d.IsNil() {
		return false
	}
	for _, i := range ids {
		if d.ID().Equal(i.ID()) {
			return true
		}
	}
	return false
}

// CopyRef returns a copy of a reference.
func (d *PropertyItemID) CopyRef() *PropertyItemID {
	if d.IsNilRef() {
		return nil
	}
	d2 := *d
	return &d2
}

// IDRef returns a reference of a domain id.
func (d *PropertyItemID) IDRef() *ID {
	if d.IsNilRef() {
		return nil
	}
	id := ID(*d)
	return &id
}

// StringRef returns a reference of a string representation.
func (d *PropertyItemID) StringRef() *string {
	if d.IsNilRef() {
		return nil
	}
	id := ID(*d).String()
	return &id
}

// MarhsalJSON implements json.Marhsaler interface
func (d *PropertyItemID) MarhsalJSON() ([]byte, error) {
	if d.IsNilRef() {
		return nil, nil
	}
	return json.Marshal(d.String())
}

// UnmarhsalJSON implements json.Unmarshaler interface
func (d *PropertyItemID) UnmarhsalJSON(bs []byte) (err error) {
	var idstr string
	if err = json.Unmarshal(bs, &idstr); err != nil {
		return
	}
	*d, err = PropertyItemIDFrom(idstr)
	return
}

// MarshalText implements encoding.TextMarshaler interface
func (d *PropertyItemID) MarshalText() ([]byte, error) {
	if d.IsNilRef() {
		return nil, nil
	}
	return []byte(d.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler interface
func (d *PropertyItemID) UnmarshalText(text []byte) (err error) {
	*d, err = PropertyItemIDFrom(string(text))
	return
}

// IsNil returns true if a ID is zero-value
func (d PropertyItemID) IsNil() bool {
	return ID(d).IsNil()
}

// IsNilRef returns true if a ID is nil or zero-value
func (d *PropertyItemID) IsNilRef() bool {
	return d == nil || ID(*d).IsNil()
}

// PropertyItemIDsToStrings converts IDs into a string slice.
func PropertyItemIDsToStrings(ids []PropertyItemID) []string {
	strs := make([]string, 0, len(ids))
	for _, i := range ids {
		strs = append(strs, i.String())
	}
	return strs
}

// PropertyItemIDsFrom converts a string slice into a ID slice.
func PropertyItemIDsFrom(ids []string) ([]PropertyItemID, error) {
	dids := make([]PropertyItemID, 0, len(ids))
	for _, i := range ids {
		did, err := PropertyItemIDFrom(i)
		if err != nil {
			return nil, err
		}
		dids = append(dids, did)
	}
	return dids, nil
}

// PropertyItemIDsFromID converts a generic ID slice into a ID slice.
func PropertyItemIDsFromID(ids []ID) []PropertyItemID {
	dids := make([]PropertyItemID, 0, len(ids))
	for _, i := range ids {
		dids = append(dids, PropertyItemID(i))
	}
	return dids
}

// PropertyItemIDsFromIDRef converts a ref of a generic ID slice into a ID slice.
func PropertyItemIDsFromIDRef(ids []*ID) []PropertyItemID {
	dids := make([]PropertyItemID, 0, len(ids))
	for _, i := range ids {
		if i != nil {
			dids = append(dids, PropertyItemID(*i))
		}
	}
	return dids
}

// PropertyItemIDsToID converts a ID slice into a generic ID slice.
func PropertyItemIDsToID(ids []PropertyItemID) []ID {
	dids := make([]ID, 0, len(ids))
	for _, i := range ids {
		dids = append(dids, i.ID())
	}
	return dids
}

// PropertyItemIDsToIDRef converts a ID ref slice into a generic ID ref slice.
func PropertyItemIDsToIDRef(ids []*PropertyItemID) []*ID {
	dids := make([]*ID, 0, len(ids))
	for _, i := range ids {
		dids = append(dids, i.IDRef())
	}
	return dids
}

// PropertyItemIDSet represents a set of PropertyItemIDs
type PropertyItemIDSet struct {
	m map[PropertyItemID]struct{}
	s []PropertyItemID
}

// NewPropertyItemIDSet creates a new PropertyItemIDSet
func NewPropertyItemIDSet() *PropertyItemIDSet {
	return &PropertyItemIDSet{}
}

// Add adds a new ID if it does not exists in the set
func (s *PropertyItemIDSet) Add(p ...PropertyItemID) {
	if s == nil || p == nil {
		return
	}
	if s.m == nil {
		s.m = map[PropertyItemID]struct{}{}
	}
	for _, i := range p {
		if _, ok := s.m[i]; !ok {
			if s.s == nil {
				s.s = []PropertyItemID{}
			}
			s.m[i] = struct{}{}
			s.s = append(s.s, i)
		}
	}
}

// AddRef adds a new ID ref if it does not exists in the set
func (s *PropertyItemIDSet) AddRef(p *PropertyItemID) {
	if s == nil || p == nil {
		return
	}
	s.Add(*p)
}

// Has checks if the ID exists in the set
func (s *PropertyItemIDSet) Has(p PropertyItemID) bool {
	if s == nil || s.m == nil {
		return false
	}
	_, ok := s.m[p]
	return ok
}

// Clear clears all stored IDs
func (s *PropertyItemIDSet) Clear() {
	if s == nil {
		return
	}
	s.m = nil
	s.s = nil
}

// All returns stored all IDs as a slice
func (s *PropertyItemIDSet) All() []PropertyItemID {
	if s == nil {
		return nil
	}
	return append([]PropertyItemID{}, s.s...)
}

// Clone returns a cloned set
func (s *PropertyItemIDSet) Clone() *PropertyItemIDSet {
	if s == nil {
		return NewPropertyItemIDSet()
	}
	s2 := NewPropertyItemIDSet()
	s2.Add(s.s...)
	return s2
}

// Merge returns a merged set
func (s *PropertyItemIDSet) Merge(s2 *PropertyItemIDSet) *PropertyItemIDSet {
	s3 := s.Clone()
	if s2 == nil {
		return s3
	}
	s3.Add(s2.s...)
	return s3
}
