// Code generated by gen, DO NOT EDIT.

package id

import (
	"encoding/json"
	"errors"
	"testing"

	"github.com/oklog/ulid"
	"github.com/stretchr/testify/assert"
)

func TestNewSceneID(t *testing.T) {
	id := NewSceneID()
	assert.NotNil(t, id)
	ulID, err := ulid.Parse(id.String())

	assert.NotNil(t, ulID)
	assert.Nil(t, err)
}

func TestSceneIDFrom(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    string
		expected struct {
			result SceneID
			err    error
		}
	}{
		{
			name:  "Fail:Not valid string",
			input: "testMustFail",
			expected: struct {
				result SceneID
				err    error
			}{
				SceneID{},
				ErrInvalidID,
			},
		},
		{
			name:  "Fail:Not valid string",
			input: "",
			expected: struct {
				result SceneID
				err    error
			}{
				SceneID{},
				ErrInvalidID,
			},
		},
		{
			name:  "success:valid string",
			input: "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: struct {
				result SceneID
				err    error
			}{
				SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
				nil,
			},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			result, err := SceneIDFrom(tc.input)
			assert.Equal(tt, tc.expected.result, result)
			if err != nil {
				assert.True(tt, errors.As(tc.expected.err, &err))
			}
		})
	}
}

func TestMustSceneID(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name        string
		input       string
		shouldPanic bool
		expected    SceneID
	}{
		{
			name:        "Fail:Not valid string",
			input:       "testMustFail",
			shouldPanic: true,
		},
		{
			name:        "Fail:Not valid string",
			input:       "",
			shouldPanic: true,
		},
		{
			name:        "success:valid string",
			input:       "01f2r7kg1fvvffp0gmexgy5hxy",
			shouldPanic: false,
			expected:    SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			if tc.shouldPanic {
				assert.Panics(tt, func() { MustBeID(tc.input) })
				return
			}
			result := MustSceneID(tc.input)
			assert.Equal(tt, tc.expected, result)
		})
	}
}

func TestSceneIDFromRef(t *testing.T) {
	testCases := []struct {
		name     string
		input    string
		expected *SceneID
	}{
		{
			name:     "Fail:Not valid string",
			input:    "testMustFail",
			expected: nil,
		},
		{
			name:     "Fail:Not valid string",
			input:    "",
			expected: nil,
		},
		{
			name:     "success:valid string",
			input:    "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: &SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}
	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			result := SceneIDFromRef(&tc.input)
			assert.Equal(tt, tc.expected, result)
			if tc.expected != nil {
				assert.Equal(tt, *tc.expected, *result)
			}
		})
	}
}

func TestSceneIDFromRefID(t *testing.T) {
	id := New()

	subId := SceneIDFromRefID(&id)

	assert.NotNil(t, subId)
	assert.Equal(t, subId.id, id.id)
}

func TestSceneID_ID(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	idOrg := subId.ID()

	assert.Equal(t, id, idOrg)
}

func TestSceneID_String(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	assert.Equal(t, subId.String(), id.String())
}

func TestSceneID_GoString(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	assert.Equal(t, subId.GoString(), "id.SceneID("+id.String()+")")
}

func TestSceneID_RefString(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	refString := subId.StringRef()

	assert.NotNil(t, refString)
	assert.Equal(t, *refString, id.String())
}

func TestSceneID_Ref(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	subIdRef := subId.Ref()

	assert.Equal(t, *subId, *subIdRef)
}

func TestSceneID_CopyRef(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	subIdCopyRef := subId.CopyRef()

	assert.Equal(t, *subId, *subIdCopyRef)
	assert.NotSame(t, subId, subIdCopyRef)
}

func TestSceneID_IDRef(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	assert.Equal(t, id, *subId.IDRef())
}

func TestSceneID_StringRef(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	assert.Equal(t, *subId.StringRef(), id.String())
}

func TestSceneID_MarhsalJSON(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	res, err := subId.MarhsalJSON()
	exp, _ := json.Marshal(subId.String())

	assert.Nil(t, err)
	assert.Equal(t, exp, res)
}

func TestSceneID_UnmarhsalJSON(t *testing.T) {
	jsonString := "\"01f3zhkysvcxsnzepyyqtq21fb\""

	subId := &SceneID{}

	err := subId.UnmarhsalJSON([]byte(jsonString))

	assert.Nil(t, err)
	assert.Equal(t, "01f3zhkysvcxsnzepyyqtq21fb", subId.String())
}

func TestSceneID_MarshalText(t *testing.T) {
	id := New()
	subId := SceneIDFromRefID(&id)

	res, err := subId.MarshalText()

	assert.Nil(t, err)
	assert.Equal(t, []byte(id.String()), res)
}

func TestSceneID_UnmarshalText(t *testing.T) {
	text := []byte("01f3zhcaq35403zdjnd6dcm0t2")

	subId := &SceneID{}

	err := subId.UnmarshalText(text)

	assert.Nil(t, err)
	assert.Equal(t, "01f3zhcaq35403zdjnd6dcm0t2", subId.String())

}

func TestSceneID_IsNil(t *testing.T) {
	subId := SceneID{}

	assert.True(t, subId.IsNil())

	id := New()
	subId = *SceneIDFromRefID(&id)

	assert.False(t, subId.IsNil())
}

func TestSceneIDToKeys(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []SceneID
		expected []string
	}{
		{
			name:     "Empty slice",
			input:    make([]SceneID, 0),
			expected: make([]string, 0),
		},
		{
			name:     "1 element",
			input:    []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			assert.Equal(tt, tc.expected, SceneIDToKeys(tc.input))
		})
	}

}

func TestSceneIDsFrom(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []string
		expected struct {
			res []SceneID
			err error
		}
	}{
		{
			name:  "Empty slice",
			input: make([]string, 0),
			expected: struct {
				res []SceneID
				err error
			}{
				res: make([]SceneID, 0),
				err: nil,
			},
		},
		{
			name:  "1 element",
			input: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
			expected: struct {
				res []SceneID
				err error
			}{
				res: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []SceneID
				err error
			}{
				res: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []SceneID
				err error
			}{
				res: nil,
				err: ErrInvalidID,
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			if tc.expected.err != nil {
				_, err := SceneIDsFrom(tc.input)
				assert.True(tt, errors.As(ErrInvalidID, &err))
			} else {
				res, err := SceneIDsFrom(tc.input)
				assert.Equal(tt, tc.expected.res, res)
				assert.Nil(tt, err)
			}

		})
	}
}

func TestSceneIDsFromID(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name     string
		input    []ID
		expected []SceneID
	}{
		{
			name:     "Empty slice",
			input:    make([]ID, 0),
			expected: make([]SceneID, 0),
		},
		{
			name:     "1 element",
			input:    []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := SceneIDsFromID(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestSceneIDsFromIDRef(t *testing.T) {
	t.Parallel()

	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")

	testCases := []struct {
		name     string
		input    []*ID
		expected []SceneID
	}{
		{
			name:     "Empty slice",
			input:    make([]*ID, 0),
			expected: make([]SceneID, 0),
		},
		{
			name:     "1 element",
			input:    []*ID{&id1},
			expected: []SceneID{MustSceneID(id1.String())},
		},
		{
			name:  "multiple elements",
			input: []*ID{&id1, &id2, &id3},
			expected: []SceneID{
				MustSceneID(id1.String()),
				MustSceneID(id2.String()),
				MustSceneID(id3.String()),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := SceneIDsFromIDRef(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestSceneIDsToID(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    []SceneID
		expected []ID
	}{
		{
			name:     "Empty slice",
			input:    make([]SceneID, 0),
			expected: make([]ID, 0),
		},
		{
			name:     "1 element",
			input:    []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := SceneIDsToID(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestSceneIDsToIDRef(t *testing.T) {
	t.Parallel()

	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	subId1 := MustSceneID(id1.String())
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	subId2 := MustSceneID(id2.String())
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")
	subId3 := MustSceneID(id3.String())

	testCases := []struct {
		name     string
		input    []*SceneID
		expected []*ID
	}{
		{
			name:     "Empty slice",
			input:    make([]*SceneID, 0),
			expected: make([]*ID, 0),
		},
		{
			name:     "1 element",
			input:    []*SceneID{&subId1},
			expected: []*ID{&id1},
		},
		{
			name:     "multiple elements",
			input:    []*SceneID{&subId1, &subId2, &subId3},
			expected: []*ID{&id1, &id2, &id3},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			res := SceneIDsToIDRef(tc.input)
			assert.Equal(tt, tc.expected, res)
		})
	}
}

func TestNewSceneIDSet(t *testing.T) {
	SceneIdSet := NewSceneIDSet()

	assert.NotNil(t, SceneIdSet)
	assert.Empty(t, SceneIdSet.m)
	assert.Empty(t, SceneIdSet.s)
}

func TestSceneIDSet_Add(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    []SceneID
		expected *SceneIDSet
	}{
		{
			name:  "Empty slice",
			input: make([]SceneID, 0),
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{},
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
		{
			name: "multiple elements with duplication",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			set := NewSceneIDSet()
			set.Add(tc.input...)
			assert.Equal(tt, tc.expected, set)
		})
	}
}

func TestSceneIDSet_AddRef(t *testing.T) {
	t.Parallel()

	SceneId := MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")

	testCases := []struct {
		name     string
		input    *SceneID
		expected *SceneIDSet
	}{
		{
			name:  "Empty slice",
			input: nil,
			expected: &SceneIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: &SceneId,
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			set := NewSceneIDSet()
			set.AddRef(tc.input)
			assert.Equal(tt, tc.expected, set)
		})
	}
}

func TestSceneIDSet_Has(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name  string
		input struct {
			SceneIDSet
			SceneID
		}
		expected bool
	}{
		{
			name: "Empty Set",
			input: struct {
				SceneIDSet
				SceneID
			}{SceneIDSet: SceneIDSet{}, SceneID: MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: false,
		},
		{
			name: "Set Contains the element",
			input: struct {
				SceneIDSet
				SceneID
			}{SceneIDSet: SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			}, SceneID: MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: true,
		},
		{
			name: "Set does not Contains the element",
			input: struct {
				SceneIDSet
				SceneID
			}{SceneIDSet: SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			}, SceneID: MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: false,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			assert.Equal(tt, tc.expected, tc.input.SceneIDSet.Has(tc.input.SceneID))
		})
	}
}

func TestSceneIDSet_Clear(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    SceneIDSet
		expected SceneIDSet
	}{
		{
			name:  "Empty Set",
			input: SceneIDSet{},
			expected: SceneIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name: "Set Contains the element",
			input: SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: SceneIDSet{
				m: nil,
				s: nil,
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			set := tc.input
			p := &set
			p.Clear()
			assert.Equal(tt, tc.expected, *p)
		})
	}
}

func TestSceneIDSet_All(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    *SceneIDSet
		expected []SceneID
	}{
		{
			name: "Empty slice",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{},
				s: nil,
			},
			expected: make([]SceneID, 0),
		},
		{
			name: "1 element",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
		},
		{
			name: "multiple elements",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			assert.Equal(tt, tc.expected, tc.input.All())
		})
	}
}

func TestSceneIDSet_Clone(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name     string
		input    *SceneIDSet
		expected *SceneIDSet
	}{
		{
			name:     "nil set",
			input:    nil,
			expected: NewSceneIDSet(),
		},
		{
			name:     "Empty set",
			input:    NewSceneIDSet(),
			expected: NewSceneIDSet(),
		},
		{
			name: "1 element",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()
			clone := tc.input.Clone()
			assert.Equal(tt, tc.expected, clone)
			assert.False(tt, tc.input == clone)
		})
	}
}

func TestSceneIDSet_Merge(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name  string
		input struct {
			a *SceneIDSet
			b *SceneIDSet
		}
		expected *SceneIDSet
	}{
		{
			name: "Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{},
				b: &SceneIDSet{},
			},
			expected: &SceneIDSet{},
		},
		{
			name: "1 Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &SceneIDSet{},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "2 non Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
				},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): struct{}{},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): struct{}{},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				},
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(tt *testing.T) {
			tt.Parallel()

			assert.Equal(tt, tc.expected, tc.input.a.Merge(tc.input.b))
		})
	}
}
