// Code generated by gen, DO NOT EDIT.

package id

import (
	"encoding/json"
	"testing"

	"github.com/oklog/ulid"
	"github.com/stretchr/testify/assert"
)

func TestNewSceneID(t *testing.T) {
	id := NewSceneID()
	assert.NotNil(t, id)
	u, err := ulid.Parse(id.String())
	assert.NotNil(t, u)
	assert.Nil(t, err)
}

func TestSceneIDFrom(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected struct {
			result SceneID
			err    error
		}
	}{
		{
			name:  "Fail:Not valid string",
			input: "testMustFail",
			expected: struct {
				result SceneID
				err    error
			}{
				result: SceneID{},
				err:    ErrInvalidID,
			},
		},
		{
			name:  "Fail:Not valid string",
			input: "",
			expected: struct {
				result SceneID
				err    error
			}{
				result: SceneID{},
				err:    ErrInvalidID,
			},
		},
		{
			name:  "success:valid string",
			input: "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: struct {
				result SceneID
				err    error
			}{
				result: SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
				err:    nil,
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result, err := SceneIDFrom(tt.input)
			assert.Equal(t, tt.expected.result, result)
			if tt.expected.err != nil {
				assert.Equal(t, tt.expected.err, err)
			}
		})
	}
}

func TestMustSceneID(t *testing.T) {
	tests := []struct {
		name        string
		input       string
		shouldPanic bool
		expected    SceneID
	}{
		{
			name:        "Fail:Not valid string",
			input:       "testMustFail",
			shouldPanic: true,
		},
		{
			name:        "Fail:Not valid string",
			input:       "",
			shouldPanic: true,
		},
		{
			name:        "success:valid string",
			input:       "01f2r7kg1fvvffp0gmexgy5hxy",
			shouldPanic: false,
			expected:    SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if tt.shouldPanic {
				assert.Panics(t, func() { MustBeID(tt.input) })
				return
			}
			result := MustSceneID(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestSceneIDFromRef(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected *SceneID
	}{
		{
			name:     "Fail:Not valid string",
			input:    "testMustFail",
			expected: nil,
		},
		{
			name:     "Fail:Not valid string",
			input:    "",
			expected: nil,
		},
		{
			name:     "success:valid string",
			input:    "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: &SceneID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result := SceneIDFromRef(&tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestSceneIDFromRefID(t *testing.T) {
	id := New()
	id2 := SceneIDFromRefID(&id)
	assert.Equal(t, id.id, id2.id)
	assert.Nil(t, SceneIDFromRefID(nil))
	assert.Nil(t, SceneIDFromRefID(&ID{}))
}

func TestSceneID_ID(t *testing.T) {
	id := New()
	id2 := SceneIDFromRefID(&id)
	assert.Equal(t, id, id2.ID())
}

func TestSceneID_String(t *testing.T) {
	id := New()
	id2 := SceneIDFromRefID(&id)
	assert.Equal(t, id.String(), id2.String())
	assert.Equal(t, "", SceneID{}.String())
}

func TestSceneID_RefString(t *testing.T) {
	id := NewSceneID()
	assert.Equal(t, id.String(), *id.RefString())
	assert.Nil(t, SceneID{}.RefString())
}

func TestSceneID_GoString(t *testing.T) {
	id := New()
	id2 := SceneIDFromRefID(&id)
	assert.Equal(t, "SceneID("+id.String()+")", id2.GoString())
	assert.Equal(t, "SceneID()", SceneID{}.GoString())
}

func TestSceneID_Ref(t *testing.T) {
	id := NewSceneID()
	assert.Equal(t, SceneID(id), *id.Ref())
	assert.Nil(t, (&SceneID{}).Ref())
}

func TestSceneID_Contains(t *testing.T) {
	id := NewSceneID()
	id2 := NewSceneID()
	assert.True(t, id.Contains([]SceneID{id, id2}))
	assert.False(t, SceneID{}.Contains([]SceneID{id, id2, {}}))
	assert.False(t, id.Contains([]SceneID{id2}))
}

func TestSceneID_CopyRef(t *testing.T) {
	id := NewSceneID().Ref()
	id2 := id.CopyRef()
	assert.Equal(t, id, id2)
	assert.NotSame(t, id, id2)
	assert.Nil(t, (*SceneID)(nil).CopyRef())
}

func TestSceneID_IDRef(t *testing.T) {
	id := New()
	id2 := SceneIDFromRefID(&id)
	assert.Equal(t, &id, id2.IDRef())
	assert.Nil(t, (&SceneID{}).IDRef())
	assert.Nil(t, (*SceneID)(nil).IDRef())
}

func TestSceneID_StringRef(t *testing.T) {
	id := NewSceneID()
	assert.Equal(t, id.String(), *id.StringRef())
	assert.Nil(t, (&SceneID{}).StringRef())
	assert.Nil(t, (*SceneID)(nil).StringRef())
}

func TestSceneID_MarhsalJSON(t *testing.T) {
	id := NewSceneID()
	res, err := id.MarhsalJSON()
	assert.Nil(t, err)
	exp, _ := json.Marshal(id.String())
	assert.Equal(t, exp, res)

	res, err = (&SceneID{}).MarhsalJSON()
	assert.Nil(t, err)
	assert.Nil(t, res)

	res, err = (*SceneID)(nil).MarhsalJSON()
	assert.Nil(t, err)
	assert.Nil(t, res)
}

func TestSceneID_UnmarhsalJSON(t *testing.T) {
	jsonString := "\"01f3zhkysvcxsnzepyyqtq21fb\""
	id := MustSceneID("01f3zhkysvcxsnzepyyqtq21fb")
	id2 := &SceneID{}
	err := id2.UnmarhsalJSON([]byte(jsonString))
	assert.Nil(t, err)
	assert.Equal(t, id, *id2)
}

func TestSceneID_MarshalText(t *testing.T) {
	id := New()
	res, err := SceneIDFromRefID(&id).MarshalText()
	assert.Nil(t, err)
	assert.Equal(t, []byte(id.String()), res)

	res, err = (&SceneID{}).MarshalText()
	assert.Nil(t, err)
	assert.Nil(t, res)

	res, err = (*SceneID)(nil).MarshalText()
	assert.Nil(t, err)
	assert.Nil(t, res)
}

func TestSceneID_UnmarshalText(t *testing.T) {
	text := []byte("01f3zhcaq35403zdjnd6dcm0t2")
	id2 := &SceneID{}
	err := id2.UnmarshalText(text)
	assert.Nil(t, err)
	assert.Equal(t, "01f3zhcaq35403zdjnd6dcm0t2", id2.String())
}

func TestSceneID_IsNil(t *testing.T) {
	assert.True(t, SceneID{}.IsNil())
	assert.False(t, NewSceneID().IsNil())
}

func TestSceneID_IsNilRef(t *testing.T) {
	assert.True(t, SceneID{}.Ref().IsNilRef())
	assert.True(t, (*SceneID)(nil).IsNilRef())
	assert.False(t, NewSceneID().Ref().IsNilRef())
}

func TestSceneIDsToStrings(t *testing.T) {
	tests := []struct {
		name     string
		input    []SceneID
		expected []string
	}{
		{
			name:     "Empty slice",
			input:    make([]SceneID, 0),
			expected: make([]string, 0),
		},
		{
			name:     "1 element",
			input:    []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.expected, SceneIDsToStrings(tt.input))
		})
	}
}

func TestSceneIDsFrom(t *testing.T) {
	tests := []struct {
		name     string
		input    []string
		expected struct {
			res []SceneID
			err error
		}
	}{
		{
			name:  "Empty slice",
			input: make([]string, 0),
			expected: struct {
				res []SceneID
				err error
			}{
				res: make([]SceneID, 0),
				err: nil,
			},
		},
		{
			name:  "1 element",
			input: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
			expected: struct {
				res []SceneID
				err error
			}{
				res: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []SceneID
				err error
			}{
				res: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
				err: nil,
			},
		},
		{
			name: "error",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"x",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []SceneID
				err error
			}{
				res: nil,
				err: ErrInvalidID,
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res, err := SceneIDsFrom(tc.input)
			if tc.expected.err != nil {
				assert.Equal(t, tc.expected.err, err)
				assert.Nil(t, res)
			} else {
				assert.Nil(t, err)
				assert.Equal(t, tc.expected.res, res)
			}
		})
	}
}

func TestSceneIDsFromID(t *testing.T) {
	tests := []struct {
		name     string
		input    []ID
		expected []SceneID
	}{
		{
			name:     "Empty slice",
			input:    make([]ID, 0),
			expected: make([]SceneID, 0),
		},
		{
			name:     "1 element",
			input:    []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := SceneIDsFromID(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestSceneIDsFromIDRef(t *testing.T) {
	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")

	tests := []struct {
		name     string
		input    []*ID
		expected []SceneID
	}{
		{
			name:     "Empty slice",
			input:    make([]*ID, 0),
			expected: make([]SceneID, 0),
		},
		{
			name:     "1 element",
			input:    []*ID{&id1},
			expected: []SceneID{MustSceneID(id1.String())},
		},
		{
			name:  "multiple elements",
			input: []*ID{&id1, &id2, &id3},
			expected: []SceneID{
				MustSceneID(id1.String()),
				MustSceneID(id2.String()),
				MustSceneID(id3.String()),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := SceneIDsFromIDRef(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestSceneIDsToID(t *testing.T) {
	tests := []struct {
		name     string
		input    []SceneID
		expected []ID
	}{
		{
			name:     "Empty slice",
			input:    make([]SceneID, 0),
			expected: make([]ID, 0),
		},
		{
			name:     "1 element",
			input:    []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := SceneIDsToID(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestSceneIDsToIDRef(t *testing.T) {
	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id21 := MustSceneID(id1.String())
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id22 := MustSceneID(id2.String())
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")
	id23 := MustSceneID(id3.String())

	tests := []struct {
		name     string
		input    []*SceneID
		expected []*ID
	}{
		{
			name:     "Empty slice",
			input:    make([]*SceneID, 0),
			expected: make([]*ID, 0),
		},
		{
			name:     "1 element",
			input:    []*SceneID{&id21},
			expected: []*ID{&id1},
		},
		{
			name:     "multiple elements",
			input:    []*SceneID{&id21, &id22, &id23},
			expected: []*ID{&id1, &id2, &id3},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := SceneIDsToIDRef(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestNewSceneIDSet(t *testing.T) {
	SceneIdSet := NewSceneIDSet()
	assert.NotNil(t, SceneIdSet)
	assert.Empty(t, SceneIdSet.m)
	assert.Empty(t, SceneIdSet.s)
}

func TestSceneIDSet_Add(t *testing.T) {
	tests := []struct {
		name     string
		input    []SceneID
		expected *SceneIDSet
	}{
		{
			name:  "Empty slice",
			input: make([]SceneID, 0),
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{},
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
		{
			name: "multiple elements with duplication",
			input: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			set := NewSceneIDSet()
			set.Add(tc.input...)
			assert.Equal(t, tc.expected, set)
		})
	}
}

func TestSceneIDSet_AddRef(t *testing.T) {
	tests := []struct {
		name     string
		input    *SceneID
		expected *SceneIDSet
	}{
		{
			name:  "Empty slice",
			input: nil,
			expected: &SceneIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: MustSceneID("01f3zhcaq35403zdjnd6dcm0t1").Ref(),
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			set := NewSceneIDSet()
			set.AddRef(tc.input)
			assert.Equal(t, tc.expected, set)
		})
	}
}

func TestSceneIDSet_Has(t *testing.T) {
	tests := []struct {
		name     string
		target   *SceneIDSet
		input    SceneID
		expected bool
	}{
		{
			name:     "Empty Set",
			target:   &SceneIDSet{},
			input:    MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
			expected: false,
		},
		{
			name: "Set Contains the element",
			target: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			input:    MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
			expected: true,
		},
		{
			name: "Set does not Contains the element",
			target: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			input:    MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
			expected: false,
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.target.Has(tc.input))
		})
	}
}

func TestSceneIDSet_Clear(t *testing.T) {
	tests := []struct {
		name     string
		input    *SceneIDSet
		expected *SceneIDSet
	}{
		{
			name:     "Empty set",
			input:    &SceneIDSet{},
			expected: &SceneIDSet{},
		},
		{
			name:     "Nil set",
			input:    nil,
			expected: nil,
		},
		{
			name: "Contains the element",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &SceneIDSet{
				m: nil,
				s: nil,
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			tc.input.Clear()
			assert.Equal(t, tc.expected, tc.input)
		})
	}
}

func TestSceneIDSet_All(t *testing.T) {
	tests := []struct {
		name     string
		input    *SceneIDSet
		expected []SceneID
	}{
		{
			name: "Empty",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{},
				s: nil,
			},
			expected: make([]SceneID, 0),
		},
		{
			name:     "Nil",
			input:    nil,
			expected: nil,
		},
		{
			name: "1 element",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
		},
		{
			name: "multiple elements",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: []SceneID{
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.input.All())
		})
	}
}

func TestSceneIDSet_Clone(t *testing.T) {
	tests := []struct {
		name     string
		input    *SceneIDSet
		expected *SceneIDSet
	}{
		{
			name:     "nil set",
			input:    nil,
			expected: NewSceneIDSet(),
		},
		{
			name:     "Empty set",
			input:    NewSceneIDSet(),
			expected: NewSceneIDSet(),
		},
		{
			name: "1 element",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			clone := tc.input.Clone()
			assert.Equal(t, tc.expected, clone)
			assert.NotSame(t, tc.input, clone)
		})
	}
}

func TestSceneIDSet_Merge(t *testing.T) {
	tests := []struct {
		name  string
		input struct {
			a *SceneIDSet
			b *SceneIDSet
		}
		expected *SceneIDSet
	}{
		{
			name: "Nil Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: nil,
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{},
				b: &SceneIDSet{},
			},
			expected: &SceneIDSet{},
		},
		{
			name: "1 Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &SceneIDSet{},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "2 non Empty Set",
			input: struct {
				a *SceneIDSet
				b *SceneIDSet
			}{
				a: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &SceneIDSet{
					m: map[SceneID]struct{}{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {}},
					s: []SceneID{MustSceneID("01f3zhcaq35403zdjnd6dcm0t2")},
				},
			},
			expected: &SceneIDSet{
				m: map[SceneID]struct{}{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"): {},
				},
				s: []SceneID{
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustSceneID("01f3zhcaq35403zdjnd6dcm0t2"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.input.a.Merge(tc.input.b))
		})
	}
}
