// Code generated by gen, DO NOT EDIT.

package id

import (
	"encoding/json"
	"testing"

	"github.com/oklog/ulid"
	"github.com/stretchr/testify/assert"
)

func TestNewTagID(t *testing.T) {
	id := NewTagID()
	assert.NotNil(t, id)
	u, err := ulid.Parse(id.String())
	assert.NotNil(t, u)
	assert.Nil(t, err)
}

func TestTagIDFrom(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected struct {
			result TagID
			err    error
		}
	}{
		{
			name:  "Fail:Not valid string",
			input: "testMustFail",
			expected: struct {
				result TagID
				err    error
			}{
				result: TagID{},
				err:    ErrInvalidID,
			},
		},
		{
			name:  "Fail:Not valid string",
			input: "",
			expected: struct {
				result TagID
				err    error
			}{
				result: TagID{},
				err:    ErrInvalidID,
			},
		},
		{
			name:  "success:valid string",
			input: "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: struct {
				result TagID
				err    error
			}{
				result: TagID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
				err:    nil,
			},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result, err := TagIDFrom(tt.input)
			assert.Equal(t, tt.expected.result, result)
			if tt.expected.err != nil {
				assert.Equal(t, tt.expected.err, err)
			}
		})
	}
}

func TestMustTagID(t *testing.T) {
	tests := []struct {
		name        string
		input       string
		shouldPanic bool
		expected    TagID
	}{
		{
			name:        "Fail:Not valid string",
			input:       "testMustFail",
			shouldPanic: true,
		},
		{
			name:        "Fail:Not valid string",
			input:       "",
			shouldPanic: true,
		},
		{
			name:        "success:valid string",
			input:       "01f2r7kg1fvvffp0gmexgy5hxy",
			shouldPanic: false,
			expected:    TagID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if tt.shouldPanic {
				assert.Panics(t, func() { MustBeID(tt.input) })
				return
			}
			result := MustTagID(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestTagIDFromRef(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected *TagID
	}{
		{
			name:     "Fail:Not valid string",
			input:    "testMustFail",
			expected: nil,
		},
		{
			name:     "Fail:Not valid string",
			input:    "",
			expected: nil,
		},
		{
			name:     "success:valid string",
			input:    "01f2r7kg1fvvffp0gmexgy5hxy",
			expected: &TagID{ulid.MustParse("01f2r7kg1fvvffp0gmexgy5hxy")},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result := TagIDFromRef(&tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestTagIDFromRefID(t *testing.T) {
	id := New()
	id2 := TagIDFromRefID(&id)
	assert.Equal(t, id.id, id2.id)
	assert.Nil(t, TagIDFromRefID(nil))
	assert.Nil(t, TagIDFromRefID(&ID{}))
}

func TestTagID_ID(t *testing.T) {
	id := New()
	id2 := TagIDFromRefID(&id)
	assert.Equal(t, id, id2.ID())
}

func TestTagID_String(t *testing.T) {
	id := New()
	id2 := TagIDFromRefID(&id)
	assert.Equal(t, id.String(), id2.String())
	assert.Equal(t, "", TagID{}.String())
}

func TestTagID_RefString(t *testing.T) {
	id := NewTagID()
	assert.Equal(t, id.String(), *id.RefString())
	assert.Nil(t, TagID{}.RefString())
}

func TestTagID_GoString(t *testing.T) {
	id := New()
	id2 := TagIDFromRefID(&id)
	assert.Equal(t, "TagID("+id.String()+")", id2.GoString())
	assert.Equal(t, "TagID()", TagID{}.GoString())
}

func TestTagID_Ref(t *testing.T) {
	id := NewTagID()
	assert.Equal(t, TagID(id), *id.Ref())
	assert.Nil(t, (&TagID{}).Ref())
}

func TestTagID_Contains(t *testing.T) {
	id := NewTagID()
	id2 := NewTagID()
	assert.True(t, id.Contains([]TagID{id, id2}))
	assert.False(t, TagID{}.Contains([]TagID{id, id2, {}}))
	assert.False(t, id.Contains([]TagID{id2}))
}

func TestTagID_CopyRef(t *testing.T) {
	id := NewTagID().Ref()
	id2 := id.CopyRef()
	assert.Equal(t, id, id2)
	assert.NotSame(t, id, id2)
	assert.Nil(t, (*TagID)(nil).CopyRef())
}

func TestTagID_IDRef(t *testing.T) {
	id := New()
	id2 := TagIDFromRefID(&id)
	assert.Equal(t, &id, id2.IDRef())
	assert.Nil(t, (&TagID{}).IDRef())
	assert.Nil(t, (*TagID)(nil).IDRef())
}

func TestTagID_StringRef(t *testing.T) {
	id := NewTagID()
	assert.Equal(t, id.String(), *id.StringRef())
	assert.Nil(t, (&TagID{}).StringRef())
	assert.Nil(t, (*TagID)(nil).StringRef())
}

func TestTagID_MarhsalJSON(t *testing.T) {
	id := NewTagID()
	res, err := id.MarhsalJSON()
	assert.Nil(t, err)
	exp, _ := json.Marshal(id.String())
	assert.Equal(t, exp, res)

	res, err = (&TagID{}).MarhsalJSON()
	assert.Nil(t, err)
	assert.Nil(t, res)

	res, err = (*TagID)(nil).MarhsalJSON()
	assert.Nil(t, err)
	assert.Nil(t, res)
}

func TestTagID_UnmarhsalJSON(t *testing.T) {
	jsonString := "\"01f3zhkysvcxsnzepyyqtq21fb\""
	id := MustTagID("01f3zhkysvcxsnzepyyqtq21fb")
	id2 := &TagID{}
	err := id2.UnmarhsalJSON([]byte(jsonString))
	assert.Nil(t, err)
	assert.Equal(t, id, *id2)
}

func TestTagID_MarshalText(t *testing.T) {
	id := New()
	res, err := TagIDFromRefID(&id).MarshalText()
	assert.Nil(t, err)
	assert.Equal(t, []byte(id.String()), res)

	res, err = (&TagID{}).MarshalText()
	assert.Nil(t, err)
	assert.Nil(t, res)

	res, err = (*TagID)(nil).MarshalText()
	assert.Nil(t, err)
	assert.Nil(t, res)
}

func TestTagID_UnmarshalText(t *testing.T) {
	text := []byte("01f3zhcaq35403zdjnd6dcm0t2")
	id2 := &TagID{}
	err := id2.UnmarshalText(text)
	assert.Nil(t, err)
	assert.Equal(t, "01f3zhcaq35403zdjnd6dcm0t2", id2.String())
}

func TestTagID_IsNil(t *testing.T) {
	assert.True(t, TagID{}.IsNil())
	assert.False(t, NewTagID().IsNil())
}

func TestTagID_IsNilRef(t *testing.T) {
	assert.True(t, TagID{}.Ref().IsNilRef())
	assert.True(t, (*TagID)(nil).IsNilRef())
	assert.False(t, NewTagID().Ref().IsNilRef())
}

func TestTagIDsToStrings(t *testing.T) {
	tests := []struct {
		name     string
		input    []TagID
		expected []string
	}{
		{
			name:     "Empty slice",
			input:    make([]TagID, 0),
			expected: make([]string, 0),
		},
		{
			name:     "1 element",
			input:    []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
		},
		{
			name: "multiple elements",
			input: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.expected, TagIDsToStrings(tt.input))
		})
	}
}

func TestTagIDsFrom(t *testing.T) {
	tests := []struct {
		name     string
		input    []string
		expected struct {
			res []TagID
			err error
		}
	}{
		{
			name:  "Empty slice",
			input: make([]string, 0),
			expected: struct {
				res []TagID
				err error
			}{
				res: make([]TagID, 0),
				err: nil,
			},
		},
		{
			name:  "1 element",
			input: []string{"01f3zhcaq35403zdjnd6dcm0t2"},
			expected: struct {
				res []TagID
				err error
			}{
				res: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t2")},
				err: nil,
			},
		},
		{
			name: "multiple elements",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"01f3zhcaq35403zdjnd6dcm0t2",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []TagID
				err error
			}{
				res: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
				err: nil,
			},
		},
		{
			name: "error",
			input: []string{
				"01f3zhcaq35403zdjnd6dcm0t1",
				"x",
				"01f3zhcaq35403zdjnd6dcm0t3",
			},
			expected: struct {
				res []TagID
				err error
			}{
				res: nil,
				err: ErrInvalidID,
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res, err := TagIDsFrom(tc.input)
			if tc.expected.err != nil {
				assert.Equal(t, tc.expected.err, err)
				assert.Nil(t, res)
			} else {
				assert.Nil(t, err)
				assert.Equal(t, tc.expected.res, res)
			}
		})
	}
}

func TestTagIDsFromID(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name     string
		input    []ID
		expected []TagID
	}{
		{
			name:     "Empty slice",
			input:    make([]ID, 0),
			expected: make([]TagID, 0),
		},
		{
			name:     "1 element",
			input:    []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := TagIDsFromID(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestTagIDsFromIDRef(t *testing.T) {
	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")

	tests := []struct {
		name     string
		input    []*ID
		expected []TagID
	}{
		{
			name:     "Empty slice",
			input:    make([]*ID, 0),
			expected: make([]TagID, 0),
		},
		{
			name:     "1 element",
			input:    []*ID{&id1},
			expected: []TagID{MustTagID(id1.String())},
		},
		{
			name:  "multiple elements",
			input: []*ID{&id1, &id2, &id3},
			expected: []TagID{
				MustTagID(id1.String()),
				MustTagID(id2.String()),
				MustTagID(id3.String()),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := TagIDsFromIDRef(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestTagIDsToID(t *testing.T) {
	tests := []struct {
		name     string
		input    []TagID
		expected []ID
	}{
		{
			name:     "Empty slice",
			input:    make([]TagID, 0),
			expected: make([]ID, 0),
		},
		{
			name:     "1 element",
			input:    []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t2")},
			expected: []ID{MustBeID("01f3zhcaq35403zdjnd6dcm0t2")},
		},
		{
			name: "multiple elements",
			input: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: []ID{
				MustBeID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustBeID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := TagIDsToID(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestTagIDsToIDRef(t *testing.T) {
	id1 := MustBeID("01f3zhcaq35403zdjnd6dcm0t1")
	id21 := MustTagID(id1.String())
	id2 := MustBeID("01f3zhcaq35403zdjnd6dcm0t2")
	id22 := MustTagID(id2.String())
	id3 := MustBeID("01f3zhcaq35403zdjnd6dcm0t3")
	id23 := MustTagID(id3.String())

	tests := []struct {
		name     string
		input    []*TagID
		expected []*ID
	}{
		{
			name:     "Empty slice",
			input:    make([]*TagID, 0),
			expected: make([]*ID, 0),
		},
		{
			name:     "1 element",
			input:    []*TagID{&id21},
			expected: []*ID{&id1},
		},
		{
			name:     "multiple elements",
			input:    []*TagID{&id21, &id22, &id23},
			expected: []*ID{&id1, &id2, &id3},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res := TagIDsToIDRef(tc.input)
			assert.Equal(t, tc.expected, res)
		})
	}
}

func TestNewTagIDSet(t *testing.T) {
	TagIdSet := NewTagIDSet()
	assert.NotNil(t, TagIdSet)
	assert.Empty(t, TagIdSet.m)
	assert.Empty(t, TagIdSet.s)
}

func TestTagIDSet_Add(t *testing.T) {
	tests := []struct {
		name     string
		input    []TagID
		expected *TagIDSet
	}{
		{
			name:  "Empty slice",
			input: make([]TagID, 0),
			expected: &TagIDSet{
				m: map[TagID]struct{}{},
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			expected: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
		{
			name: "multiple elements with duplication",
			input: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			set := NewTagIDSet()
			set.Add(tc.input...)
			assert.Equal(t, tc.expected, set)
		})
	}
}

func TestTagIDSet_AddRef(t *testing.T) {
	tests := []struct {
		name     string
		input    *TagID
		expected *TagIDSet
	}{
		{
			name:  "Empty slice",
			input: nil,
			expected: &TagIDSet{
				m: nil,
				s: nil,
			},
		},
		{
			name:  "1 element",
			input: MustTagID("01f3zhcaq35403zdjnd6dcm0t1").Ref(),
			expected: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			set := NewTagIDSet()
			set.AddRef(tc.input)
			assert.Equal(t, tc.expected, set)
		})
	}
}

func TestTagIDSet_Has(t *testing.T) {
	tests := []struct {
		name     string
		target   *TagIDSet
		input    TagID
		expected bool
	}{
		{
			name:     "Empty Set",
			target:   &TagIDSet{},
			input:    MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
			expected: false,
		},
		{
			name: "Set Contains the element",
			target: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			input:    MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
			expected: true,
		},
		{
			name: "Set does not Contains the element",
			target: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			input:    MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
			expected: false,
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.target.Has(tc.input))
		})
	}
}

func TestTagIDSet_Clear(t *testing.T) {
	tests := []struct {
		name     string
		input    *TagIDSet
		expected *TagIDSet
	}{
		{
			name:     "Empty set",
			input:    &TagIDSet{},
			expected: &TagIDSet{},
		},
		{
			name:     "Nil set",
			input:    nil,
			expected: nil,
		},
		{
			name: "Contains the element",
			input: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &TagIDSet{
				m: nil,
				s: nil,
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			tc.input.Clear()
			assert.Equal(t, tc.expected, tc.input)
		})
	}
}

func TestTagIDSet_All(t *testing.T) {
	tests := []struct {
		name     string
		input    *TagIDSet
		expected []TagID
	}{
		{
			name: "Empty",
			input: &TagIDSet{
				m: map[TagID]struct{}{},
				s: nil,
			},
			expected: make([]TagID, 0),
		},
		{
			name:     "Nil",
			input:    nil,
			expected: nil,
		},
		{
			name: "1 element",
			input: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
		},
		{
			name: "multiple elements",
			input: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: []TagID{
				MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.input.All())
		})
	}
}

func TestTagIDSet_Clone(t *testing.T) {
	tests := []struct {
		name     string
		input    *TagIDSet
		expected *TagIDSet
	}{
		{
			name:     "nil set",
			input:    nil,
			expected: NewTagIDSet(),
		},
		{
			name:     "Empty set",
			input:    NewTagIDSet(),
			expected: NewTagIDSet(),
		},
		{
			name: "1 element",
			input: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "multiple elements",
			input: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t3"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			clone := tc.input.Clone()
			assert.Equal(t, tc.expected, clone)
			assert.NotSame(t, tc.input, clone)
		})
	}
}

func TestTagIDSet_Merge(t *testing.T) {
	tests := []struct {
		name  string
		input struct {
			a *TagIDSet
			b *TagIDSet
		}
		expected *TagIDSet
	}{
		{
			name: "Nil Set",
			input: struct {
				a *TagIDSet
				b *TagIDSet
			}{
				a: &TagIDSet{
					m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: nil,
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "Empty Set",
			input: struct {
				a *TagIDSet
				b *TagIDSet
			}{
				a: &TagIDSet{},
				b: &TagIDSet{},
			},
			expected: &TagIDSet{},
		},
		{
			name: "1 Empty Set",
			input: struct {
				a *TagIDSet
				b *TagIDSet
			}{
				a: &TagIDSet{
					m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &TagIDSet{},
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
				s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
			},
		},
		{
			name: "2 non Empty Set",
			input: struct {
				a *TagIDSet
				b *TagIDSet
			}{
				a: &TagIDSet{
					m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {}},
					s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t1")},
				},
				b: &TagIDSet{
					m: map[TagID]struct{}{MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {}},
					s: []TagID{MustTagID("01f3zhcaq35403zdjnd6dcm0t2")},
				},
			},
			expected: &TagIDSet{
				m: map[TagID]struct{}{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"): {},
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"): {},
				},
				s: []TagID{
					MustTagID("01f3zhcaq35403zdjnd6dcm0t1"),
					MustTagID("01f3zhcaq35403zdjnd6dcm0t2"),
				},
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.expected, tc.input.a.Merge(tc.input.b))
		})
	}
}
