// Code generated by migrategen, DO NOT EDIT.

package migration

var migrations = map[int64]MigrationFunc{
  201217132559: AddSceneWidgetId,
  201217193948: AddSceneDefaultTile,
  210310145844: RemovePreviewToken,
  210730175108: AddSceneAlignSystem,
  220214180713: SplitSchemaOfProperties,
}
