// Code generated by go generate; DO NOT EDIT.
package errmsg

import (
	"golang.org/x/text/language"
	"github.com/reearth/reearth/server/pkg/i18n/message"
)

const (
	ErrKeyPkgProjectInvalidAlias message.ErrKey = "pkg.project.invalid_alias"
)

var ErrorMessages = map[message.ErrKey]map[language.Tag]message.ErrorMessage{
	ErrKeyPkgProjectInvalidAlias: {
		language.English: {
			Message:     "Invalid alias name: {{.aliasName}}",
			Description: "The alias '{{.aliasName}}' must be {{.minLength}}-{{.maxLength}} characters long and can only contain {{.allowedChars}}.",
		},
		language.Japanese: {
			Message:     "不正なエイリアス名です: {{.aliasName}}",
			Description: "エイリアス名は{{.minLength}}-{{.maxLength}}文字で、{{.allowedChars}}のみ使用できます。",
		},
	},
}
