export default {
  id: "01h79x1hkxcgfzpykc251kthxc",
  clusters: [],
  plugins: [
    {
      __typename: "ScenePlugin",
      property: null,
      plugin: {
        __typename: "Plugin",
        id: "reearth",
        name: "Re:Earth Official Plugin",
        extensions: [
          {
            __typename: "PluginExtension",
            extensionId: "cesium",
            description:
              "Select here to find scene settings in the right panel. This includes setting map tiles, atmospheric conditions, real lighting, and more.",
            name: "Cesium",
            translatedDescription:
              "Select here to find scene settings in the right panel. This includes setting map tiles, atmospheric conditions, real lighting, and more.",
            translatedName: "Cesium",
            icon: "",
            singleOnly: false,
            type: "VISUALIZER",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "infobox",
            description:
              "Create an information area that appears when a layer is highlighted. Text, pictures, video, etc can be added to an infobox.",
            name: "Infobox",
            translatedDescription:
              "Create an information area that appears when a layer is highlighted. Text, pictures, video, etc can be added to an infobox.",
            translatedName: "Infobox",
            icon: "",
            singleOnly: false,
            type: "INFOBOX",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "marker",
            description: "A standard map marker.",
            name: "Marker",
            translatedDescription: "A standard map marker.",
            translatedName: "Marker",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "polyline",
            description: "Polyline primitive",
            name: "Polyline",
            translatedDescription: "Polyline primitive",
            translatedName: "Polyline",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "polygon",
            description: "Polygon primitive",
            name: "Polygon",
            translatedDescription: "Polygon primitive",
            translatedName: "Polygon",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "rect",
            description: "Rectangle primitive",
            name: "Rectangle",
            translatedDescription: "Rectangle primitive",
            translatedName: "Rectangle",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "photooverlay",
            description:
              "An Icon marker that allows you to set a photo that will appear after reaching its location.",
            name: "Photo overlay",
            translatedDescription:
              "An Icon marker that allows you to set a photo that will appear after reaching its location.",
            translatedName: "Photo overlay",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "ellipsoid",
            description: "A 3D ellipsoid",
            name: "Sphere",
            translatedDescription: "A 3D ellipsoid",
            translatedName: "Sphere",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "model",
            description: "A 3D model",
            name: "3D Model",
            translatedDescription: "A 3D model",
            translatedName: "3D Model",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "tileset",
            description: '3D tiles in "3D Tiles" format',
            name: "3D Tiles",
            translatedDescription: '3D tiles in "3D Tiles" format',
            translatedName: "3D Tiles",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "resource",
            description:
              "Import your own primitives to be used instead of Re:Earth's built in ones.",
            name: "File",
            translatedDescription:
              "Import your own primitives to be used instead of Re:Earth's built in ones.",
            translatedName: "File",
            icon: "",
            singleOnly: false,
            type: "PRIMITIVE",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "textblock",
            description: "Text block",
            name: "Text",
            translatedDescription: "Text block",
            translatedName: "Text",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "imageblock",
            description: "Image block",
            name: "Image",
            translatedDescription: "Image block",
            translatedName: "Image",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "videoblock",
            description: "Video block",
            name: "Video",
            translatedDescription: "Video block",
            translatedName: "Video",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "locationblock",
            description: "Location block",
            name: "Location",
            translatedDescription: "Location block",
            translatedName: "Location",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "dlblock",
            description: "Table block",
            name: "Table",
            translatedDescription: "Table block",
            translatedName: "Table",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "htmlblock",
            description: "HTML block",
            name: "HTML",
            translatedDescription: "HTML block",
            translatedName: "HTML",
            icon: "",
            singleOnly: false,
            type: "BLOCK",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "menu",
            description: "Menu widgets",
            name: "Menu (legacy)",
            translatedDescription: "Menu widgets",
            translatedName: "Menu (legacy)",
            icon: "",
            singleOnly: true,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: false,
              },
              extended: false,
              floating: true,
              defaultLocation: null,
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "button",
            description: "Button widget",
            name: "Button",
            translatedDescription: "Button widget",
            translatedName: "Button",
            icon: "",
            singleOnly: false,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: false,
              },
              extended: false,
              floating: false,
              defaultLocation: {
                __typename: "WidgetLocation",
                zone: "OUTER",
                section: "LEFT",
                area: "TOP",
              },
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "splashscreen",
            description:
              "A unique start screen that will display on load of your archive(ex. display the archive's title).",
            name: "Splash screen",
            translatedDescription:
              "A unique start screen that will display on load of your archive(ex. display the archive's title).",
            translatedName: "Splash screen",
            icon: "",
            singleOnly: true,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: false,
              },
              extended: false,
              floating: true,
              defaultLocation: null,
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "storytelling",
            description:
              "SA feature that enables you to create a story. Connect points in a meaningful way so that your information can be consumed and understood easily.",
            name: "Storytelling",
            translatedDescription:
              "SA feature that enables you to create a story. Connect points in a meaningful way so that your information can be consumed and understood easily.",
            translatedName: "Storytelling",
            icon: "",
            singleOnly: true,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: true,
              },
              extended: false,
              floating: false,
              defaultLocation: {
                __typename: "WidgetLocation",
                zone: "OUTER",
                section: "LEFT",
                area: "BOTTOM",
              },
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "cluster",
            description: "Defines how layers are clustered together and displayed on earth.",
            name: "Cluster",
            translatedDescription:
              "Defines how layers are clustered together and displayed on earth.",
            translatedName: "Cluster",
            icon: "",
            singleOnly: false,
            type: "Cluster",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "timeline",
            description:
              "A timeline widget that allows for viewing layers and data at specific points in time.",
            name: "Timeline",
            translatedDescription:
              "A timeline widget that allows for viewing layers and data at specific points in time.",
            translatedName: "Timeline",
            icon: "",
            singleOnly: true,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: true,
              },
              extended: false,
              floating: false,
              defaultLocation: {
                __typename: "WidgetLocation",
                zone: "OUTER",
                section: "CENTER",
                area: "BOTTOM",
              },
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "navigator",
            description:
              "A navigator widget that allows for viewing the earth from various angle by operating menu.",
            name: "Navigator",
            translatedDescription:
              "A navigator widget that allows for viewing the earth from various angle by operating menu.",
            translatedName: "Navigator",
            icon: "",
            singleOnly: true,
            type: "WIDGET",
            widgetLayout: {
              __typename: "WidgetLayout",
              extendable: {
                __typename: "WidgetExtendable",
                vertically: false,
                horizontally: false,
              },
              extended: false,
              floating: false,
              defaultLocation: {
                __typename: "WidgetLocation",
                zone: "OUTER",
                section: "RIGHT",
                area: "TOP",
              },
            },
          },
          {
            __typename: "PluginExtension",
            extensionId: "story",
            description: "Storytelling story",
            name: "Story",
            translatedDescription: "Storytelling story",
            translatedName: "Story",
            icon: "",
            singleOnly: false,
            type: "Story",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "storyPage",
            description: "Storytelling Page",
            name: "Page",
            translatedDescription: "Storytelling Page",
            translatedName: "Page",
            icon: "",
            singleOnly: false,
            type: "StoryPage",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "storyBlock",
            description: "Storytelling Block",
            name: "Block",
            translatedDescription: "Storytelling Block",
            translatedName: "Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "textStoryBlock",
            description: "Storytelling Text Block",
            name: "Text Block",
            translatedDescription: "Storytelling Text Block",
            translatedName: "Text Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "mdTextStoryBlock",
            description: "Storytelling MD Text Block",
            name: "MD Test Block",
            translatedDescription: "Storytelling MD Text Block",
            translatedName: "MD Test Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "imageStoryBlock",
            description: "Storytelling Image Block",
            name: "Image Block",
            translatedDescription: "Storytelling Image Block",
            translatedName: "Image Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "videoStoryBlock",
            description: "Storytelling Video Block",
            name: "Video Block",
            translatedDescription: "Storytelling Video Block",
            translatedName: "Video Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "cameraButtonStoryBlock",
            description: "Storytelling Camera Button",
            name: "Camera Button",
            translatedDescription: "Storytelling Camera Button",
            translatedName: "Camera Button",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "linkButtonStoryBlock",
            description: "Storytelling Link Button",
            name: "Link Button",
            translatedDescription: "Storytelling Link Button",
            translatedName: "Link Button",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
          {
            __typename: "PluginExtension",
            extensionId: "timelineStoryBlock",
            description: "Storytelling Timeline Block",
            name: "Timeline Block",
            translatedDescription: "Storytelling Timeline Block",
            translatedName: "Timeline Block",
            icon: "",
            singleOnly: false,
            type: "StoryBlock",
            widgetLayout: null,
          },
        ],
      },
    },
  ],
  projectId: "01h79x1h9dj779aq637rt4sq3h",
  property: {
    __typename: "Property",
    id: "01h79x1hkxcgfzpykc29r4srvf",
    schema: {
      __typename: "PropertySchema",
      id: "reearth/cesium",
      groups: [
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "default",
          title: "Scene",
          translatedTitle: "Scene",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "camera",
              title: "Initial camera position",
              description: "The starting position of your project.",
              translatedTitle: "Initial camera position",
              translatedDescription: "The starting position of your project.",
              prefix: null,
              suffix: null,
              type: "CAMERA",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "allowEnterGround",
              title: "Enter the ground",
              description: "Set to true to allow the camera to enter the surface of the earth.",
              translatedTitle: "Enter the ground",
              translatedDescription:
                "Set to true to allow the camera to enter the surface of the earth.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "sceneMode",
              title: "Scene mode",
              description: "Specify scene mode.",
              translatedTitle: "Scene mode",
              translatedDescription: "Specify scene mode.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "3d",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "3d",
                  icon: null,
                  title: "Scene 3D",
                  translatedTitle: "Scene 3D",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "2d",
                  icon: null,
                  title: "Scene 2D",
                  translatedTitle: "Scene 2D",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "columbus",
                  icon: null,
                  title: "Columbus View",
                  translatedTitle: "Columbus View",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "skybox",
              title: "Sky",
              description: "Show the stars.",
              translatedTitle: "Sky",
              translatedDescription: "Show the stars.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: true,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "bgcolor",
              title: "Background color",
              description: "With Sky disabled, choose a background color.",
              translatedTitle: "Background color",
              translatedDescription: "With Sky disabled, choose a background color.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: "COLOR",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "ion",
              title: "Cesium Ion API access token",
              description:
                "Cesium Ion account users may use their personal API keys to be able to use their Cesium Ion assets(tile data, 3D data, etc) with their project.",
              translatedTitle: "Cesium Ion API access token",
              translatedDescription:
                "Cesium Ion account users may use their personal API keys to be able to use their Cesium Ion assets(tile data, 3D data, etc) with their project.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "vr",
              title: "VR",
              description: "Enable VR mode to split the screen into left and right.",
              translatedTitle: "VR",
              translatedDescription: "Enable VR mode to split the screen into left and right.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "tiles",
          title: "Tiles",
          translatedTitle: "Tiles",
          isList: true,
          representativeFieldId: "tile_type",
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "tile_type",
              title: "Tile type",
              description: "",
              translatedTitle: "Tile type",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "default",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "default",
                  icon: null,
                  title: "Default",
                  translatedTitle: "Default",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "default_label",
                  icon: null,
                  title: "Labelled",
                  translatedTitle: "Labelled",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "default_road",
                  icon: null,
                  title: "Road Map",
                  translatedTitle: "Road Map",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "stamen_watercolor",
                  icon: null,
                  title: "Stamen Watercolor",
                  translatedTitle: "Stamen Watercolor",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "stamen_toner",
                  icon: null,
                  title: "Stamen Toner",
                  translatedTitle: "Stamen Toner",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "open_street_map",
                  icon: null,
                  title: "OpenStreetMap",
                  translatedTitle: "OpenStreetMap",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "esri_world_topo",
                  icon: null,
                  title: "ESRI Topography",
                  translatedTitle: "ESRI Topography",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "black_marble",
                  icon: null,
                  title: "Earth at night",
                  translatedTitle: "Earth at night",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "japan_gsi_standard",
                  icon: null,
                  title: "Japan GSI Standard Map",
                  translatedTitle: "Japan GSI Standard Map",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "url",
                  icon: null,
                  title: "URL",
                  translatedTitle: "URL",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "tile_url",
              title: "Tile map URL",
              description: "",
              translatedTitle: "Tile map URL",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "tile_type",
                type: "STRING",
                value: "url",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "tile_minLevel",
              title: "Minimum zoom level",
              description: "",
              translatedTitle: "Minimum zoom level",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: null,
              ui: null,
              min: 0,
              max: 30,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "tile_maxLevel",
              title: "Maximum zoom level",
              description: "",
              translatedTitle: "Maximum zoom level",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: null,
              ui: null,
              min: 0,
              max: 30,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "tile_opacity",
              title: "Opacity",
              description: "Change the opacity of the selected tile map. Min: 0 Max: 1",
              translatedTitle: "Opacity",
              translatedDescription: "Change the opacity of the selected tile map. Min: 0 Max: 1",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: 1,
              ui: "SLIDER",
              min: 0,
              max: 1,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "terrain",
          title: "Terrain",
          translatedTitle: "Terrain",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "terrain",
              title: "Terrain",
              description: "Show elevation when close to the surface.",
              translatedTitle: "Terrain",
              translatedDescription: "Show elevation when close to the surface.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainType",
              title: "Terrain type",
              description: "Specify terrain type.",
              translatedTitle: "Terrain type",
              translatedDescription: "Specify terrain type.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "cesium",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "cesium",
                  icon: null,
                  title: "Cesium World Terrain",
                  translatedTitle: "Cesium World Terrain",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "arcgis",
                  icon: null,
                  title: "ArcGIS Terrain",
                  translatedTitle: "ArcGIS Terrain",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "cesiumion",
                  icon: null,
                  title: "Cesium Ion",
                  translatedTitle: "Cesium Ion",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainCesiumIonAsset",
              title: "Terrain Cesium Ion asset ID",
              description: "Specify the ID of a terrain asset registered on Cesium Ion.",
              translatedTitle: "Terrain Cesium Ion asset ID",
              translatedDescription: "Specify the ID of a terrain asset registered on Cesium Ion.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "terrainType",
                type: "STRING",
                value: "cesiumion",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainCesiumIonAccessToken",
              title: "Terrain Cesium Ion access token",
              description:
                "Specify a Cesium Ion access token if you want to override the access token in the scene-wide settings for this tile.",
              translatedTitle: "Terrain Cesium Ion access token",
              translatedDescription:
                "Specify a Cesium Ion access token if you want to override the access token in the scene-wide settings for this tile.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "terrainType",
                type: "STRING",
                value: "cesiumion",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainCesiumIonUrl",
              title: "Terrain URL",
              description:
                "Specify the URL of Cesium's terrain server if it is delivered on-premises rather than Cesum Ion. This takes precedence over the asset ID setting.",
              translatedTitle: "Terrain URL",
              translatedDescription:
                "Specify the URL of Cesium's terrain server if it is delivered on-premises rather than Cesum Ion. This takes precedence over the asset ID setting.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "terrainType",
                type: "STRING",
                value: "cesiumion",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainExaggeration",
              title: "Terrain exaggeration",
              description:
                "A scalar used to exaggerate the terrain. Defaults to 1.0 (no exaggeration). A value of 2.0 scales the terrain by 2x. A value of 0.0 makes the terrain completely flat.",
              translatedTitle: "Terrain exaggeration",
              translatedDescription:
                "A scalar used to exaggerate the terrain. Defaults to 1.0 (no exaggeration). A value of 2.0 scales the terrain by 2x. A value of 0.0 makes the terrain completely flat.",
              prefix: null,
              suffix: "x",
              type: "NUMBER",
              defaultValue: 1,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "terrainExaggerationRelativeHeight",
              title: "Terrain exaggeration relative height",
              description:
                "The height from which terrain is exaggerated. Defaults to 0.0. Terrain that is above this height will scale upwards and terrain that is below this height will scale downwards.",
              translatedTitle: "Terrain exaggeration relative height",
              translatedDescription:
                "The height from which terrain is exaggerated. Defaults to 0.0. Terrain that is above this height will scale upwards and terrain that is below this height will scale downwards.",
              prefix: null,
              suffix: "m",
              type: "NUMBER",
              defaultValue: 0,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "depthTestAgainstTerrain",
              title: "Hide objects under terrain",
              description:
                "Hides objects under the terrain. Depending on the loading status of the terrain, objects may be shown or hidden.",
              translatedTitle: "Hide objects under terrain",
              translatedDescription:
                "Hides objects under the terrain. Depending on the loading status of the terrain, objects may be shown or hidden.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "indicator",
          title: "Indicator",
          translatedTitle: "Indicator",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "indicator_type",
              title: "Type",
              description: "Choose how the indicator will look.",
              translatedTitle: "Type",
              translatedDescription: "Choose how the indicator will look.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "default",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "default",
                  icon: null,
                  title: "Default",
                  translatedTitle: "Default",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "crosshair",
                  icon: null,
                  title: "Crosshair",
                  translatedTitle: "Crosshair",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "custom",
                  icon: null,
                  title: "Custom",
                  translatedTitle: "Custom",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "indicator_image",
              title: "Image URL",
              description: "",
              translatedTitle: "Image URL",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "URL",
              defaultValue: null,
              ui: "IMAGE",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "indicator_type",
                type: "STRING",
                value: "custom",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "indicator_image_scale",
              title: "Image scale",
              description: "",
              translatedTitle: "Image scale",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "indicator_type",
                type: "STRING",
                value: "custom",
              },
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "theme",
          title: "Publish Theme",
          translatedTitle: "Publish Theme",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "themeType",
              title: "Theme",
              description: "Select the theme.",
              translatedTitle: "Theme",
              translatedDescription: "Select the theme.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "dark",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "dark",
                  icon: null,
                  title: "Re:Earth Dark",
                  translatedTitle: "Re:Earth Dark",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "light",
                  icon: null,
                  title: "Re:Earth Light",
                  translatedTitle: "Re:Earth Light",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "forest",
                  icon: null,
                  title: "Forest",
                  translatedTitle: "Forest",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "custom",
                  icon: null,
                  title: "Custom theme",
                  translatedTitle: "Custom theme",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "themeTextColor",
              title: "Text color",
              description: "Select a color.",
              translatedTitle: "Text color",
              translatedDescription: "Select a color.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "#434343",
              ui: "COLOR",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "themeType",
                type: "STRING",
                value: "custom",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "themeSelectColor",
              title: "Select color",
              description: "Select a color.",
              translatedTitle: "Select color",
              translatedDescription: "Select a color.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "#C52C63",
              ui: "COLOR",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "themeType",
                type: "STRING",
                value: "custom",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "themeBackgroundColor",
              title: "Background color",
              description: "Select a color.",
              translatedTitle: "Background color",
              translatedDescription: "Select a color.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "#DFE5F0",
              ui: "COLOR",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "themeType",
                type: "STRING",
                value: "custom",
              },
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "atmosphere",
          title: "Atmospheric Conditions",
          translatedTitle: "Atmospheric Conditions",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "enable_sun",
              title: "Sun",
              description: "Display the Sun.",
              translatedTitle: "Sun",
              translatedDescription: "Display the Sun.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: true,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "enable_lighting",
              title: "Lighting",
              description: "Display natural lighting from the sun.",
              translatedTitle: "Lighting",
              translatedDescription: "Display natural lighting from the sun.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "ground_atmosphere",
              title: "Ground atmosphere",
              description: "Display a lower atmospheric layer.",
              translatedTitle: "Ground atmosphere",
              translatedDescription: "Display a lower atmospheric layer.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: true,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "sky_atmosphere",
              title: "Sky atmosphere",
              description: "Display an upper atmospheric layer.",
              translatedTitle: "Sky atmosphere",
              translatedDescription: "Display an upper atmospheric layer.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: true,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "shadows",
              title: "Shadow",
              description:
                "Display shadows on the Earth. Shadows for each layers should be also enabled to see them.",
              translatedTitle: "Shadow",
              translatedDescription:
                "Display shadows on the Earth. Shadows for each layers should be also enabled to see them.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "fog",
              title: "Fog",
              description: "Display customizable fog.",
              translatedTitle: "Fog",
              translatedDescription: "Display customizable fog.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: true,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "fog_density",
              title: "Fog density",
              description: "Set a thickness to the fog. Min: 0 Max: 1",
              translatedTitle: "Fog density",
              translatedDescription: "Set a thickness to the fog. Min: 0 Max: 1",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: 0.0002,
              ui: null,
              min: 0,
              max: 1,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "brightness_shift",
              title: "Fog brightness",
              description: "Set brightness of the fog. Min: -1 Max: 1",
              translatedTitle: "Fog brightness",
              translatedDescription: "Set brightness of the fog. Min: -1 Max: 1",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: 0.03,
              ui: null,
              min: -1,
              max: 1,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "hue_shift",
              title: "Fog hue",
              description: "Set hue of the fog. Min: -1 Max: 1",
              translatedTitle: "Fog hue",
              translatedDescription: "Set hue of the fog. Min: -1 Max: 1",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: null,
              ui: null,
              min: -1,
              max: 1,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "surturation_shift",
              title: "Fog saturation",
              description: "Set saturation of the fog. Min: -1 Max: 1",
              translatedTitle: "Fog saturation",
              translatedDescription: "Set saturation of the fog. Min: -1 Max: 1",
              prefix: null,
              suffix: null,
              type: "NUMBER",
              defaultValue: null,
              ui: null,
              min: -1,
              max: 1,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "timeline",
          title: "Timeline",
          translatedTitle: "Timeline",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "animation",
              title: "Animation",
              description: "Enables animation play. If enabled, each 3D models can animate.",
              translatedTitle: "Animation",
              translatedDescription:
                "Enables animation play. If enabled, each 3D models can animate.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "visible",
              title: "Timeline",
              description: "Whether the timeline UI is displayed or not",
              translatedTitle: "Timeline",
              translatedDescription: "Whether the timeline UI is displayed or not",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "current",
              title: "Current time",
              description: "",
              translatedTitle: "Current time",
              translatedDescription: "",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: "DATETIME",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "start",
              title: "Start time",
              description:
                "If nothing is set, it will be set automatically according to the data being displayed.",
              translatedTitle: "Start time",
              translatedDescription:
                "If nothing is set, it will be set automatically according to the data being displayed.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: "DATETIME",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "stop",
              title: "Stop time",
              description:
                "If nothing is set, it will be set automatically according to the data being displayed.",
              translatedTitle: "Stop time",
              translatedDescription:
                "If nothing is set, it will be set automatically according to the data being displayed.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: "DATETIME",
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "stepType",
              title: "Tick type",
              description: "How to specify the playback speed",
              translatedTitle: "Tick type",
              translatedDescription: "How to specify the playback speed",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "rate",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "rate",
                  icon: null,
                  title: "Rate",
                  translatedTitle: "Rate",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "fixed",
                  icon: null,
                  title: "Fixed",
                  translatedTitle: "Fixed",
                },
              ],
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "multiplier",
              title: "Multiplier",
              description:
                "Specifies the playback speed as a multiple of the real time speed. Negative values can also be specified. Default is 1x.",
              translatedTitle: "Multiplier",
              translatedDescription:
                "Specifies the playback speed as a multiple of the real time speed. Negative values can also be specified. Default is 1x.",
              prefix: "x",
              suffix: null,
              type: "NUMBER",
              defaultValue: 1,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "stepType",
                type: "STRING",
                value: "rate",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "step",
              title: "Step",
              description:
                "Specifies the playback speed in seconds. Each time the screen is repeatedly drawn, it advances by the specified specified number of seconds. Negative values can also be specified. The default is 1 second.",
              translatedTitle: "Step",
              translatedDescription:
                "Specifies the playback speed in seconds. Each time the screen is repeatedly drawn, it advances by the specified specified number of seconds. Negative values can also be specified. The default is 1 second.",
              prefix: null,
              suffix: "s",
              type: "NUMBER",
              defaultValue: 1,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: {
                __typename: "PropertyCondition",
                fieldId: "stepType",
                type: "STRING",
                value: "fixed",
              },
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "rangeType",
              title: "Range",
              description:
                "Specifies the playback speed in seconds. Negative values can also be specified.",
              translatedTitle: "Range",
              translatedDescription:
                "Specifies the playback speed in seconds. Negative values can also be specified.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: "unbounded",
              ui: null,
              min: null,
              max: null,
              choices: [
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "unbounded",
                  icon: null,
                  title: "Unbounded",
                  translatedTitle: "Unbounded",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "clamped",
                  icon: null,
                  title: "Clamped",
                  translatedTitle: "Clamped",
                },
                {
                  __typename: "PropertySchemaFieldChoice",
                  key: "bounced",
                  icon: null,
                  title: "Bounced",
                  translatedTitle: "Bounced",
                },
              ],
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "cameraLimiter",
          title: "Camera Limiter",
          translatedTitle: "Camera Limiter",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "cameraLimitterEnabled",
              title: "Enable",
              description: "Enable camera limiter.",
              translatedTitle: "Enable",
              translatedDescription: "Enable camera limiter.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "cameraLimitterShowHelper",
              title: "Show helper",
              description: "Display the limiter boundaries.",
              translatedTitle: "Show helper",
              translatedDescription: "Display the limiter boundaries.",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "cameraLimitterTargetArea",
              title: "Target max height",
              description:
                "The base position of the camera movement range. This position is the center point of the limit box in the horizontal and depth directions, and is the maximum height of the movable range. The camera will not be able to zoom out beyond the height specified here.",
              translatedTitle: "Target max height",
              translatedDescription:
                "The base position of the camera movement range. This position is the center point of the limit box in the horizontal and depth directions, and is the maximum height of the movable range. The camera will not be able to zoom out beyond the height specified here.",
              prefix: null,
              suffix: null,
              type: "CAMERA",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "cameraLimitterTargetWidth",
              title: "Target width",
              description:
                "Specifies the width (longitude direction) of the box that represents the limiter boundaries.",
              translatedTitle: "Target width",
              translatedDescription:
                "Specifies the width (longitude direction) of the box that represents the limiter boundaries.",
              prefix: null,
              suffix: "m",
              type: "NUMBER",
              defaultValue: 1000000,
              ui: null,
              min: 5,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "cameraLimitterTargetLength",
              title: "Target length",
              description:
                "Specifies the depth (latitude direction) of the box that represents the limiter boundaries.",
              translatedTitle: "Target length",
              translatedDescription:
                "Specifies the depth (latitude direction) of the box that represents the limiter boundaries.",
              prefix: null,
              suffix: "m",
              type: "NUMBER",
              defaultValue: 1000000,
              ui: null,
              min: 5,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "googleAnalytics",
          title: "Google Analytics",
          translatedTitle: "Google Analytics",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "enableGA",
              title: "Enable",
              description: "Enable Google Analytics",
              translatedTitle: "Enable",
              translatedDescription: "Enable Google Analytics",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "trackingId",
              title: "Tracking ID",
              description:
                "Paste your Google Analytics tracking ID here. This will be embedded in your published project.",
              translatedTitle: "Tracking ID",
              translatedDescription:
                "Paste your Google Analytics tracking ID here. This will be embedded in your published project.",
              prefix: null,
              suffix: null,
              type: "STRING",
              defaultValue: null,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
        {
          __typename: "PropertySchemaGroup",
          schemaGroupId: "experimental",
          title: "Advanced",
          translatedTitle: "Advanced",
          isList: false,
          representativeFieldId: null,
          isAvailableIf: null,
          fields: [
            {
              __typename: "PropertySchemaField",
              fieldId: "experimental_core",
              title: "Enable advanced features",
              description: "Enable advanced features for this scene. (beta)",
              translatedTitle: "Enable advanced features",
              translatedDescription: "Enable advanced features for this scene. (beta)",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
            {
              __typename: "PropertySchemaField",
              fieldId: "experimental_sandbox",
              title: "Enable sandbox (alpha)",
              description: "Enable sandbox for plugin iframes. (alpha)",
              translatedTitle: "Enable sandbox (alpha)",
              translatedDescription: "Enable sandbox for plugin iframes. (alpha)",
              prefix: null,
              suffix: null,
              type: "BOOL",
              defaultValue: false,
              ui: null,
              min: null,
              max: null,
              choices: null,
              isAvailableIf: null,
            },
          ],
        },
      ],
    },
    items: [
      {
        __typename: "PropertyGroupList",
        id: "01h79x1hkxcgfzpykc2d9s6jjx",
        schemaGroupId: "tiles",
        groups: [
          {
            __typename: "PropertyGroup",
            id: "01h79x1hkxcgfzpykc2ebe0yx7",
            schemaGroupId: "tiles",
            fields: [],
          },
        ],
      },
    ],
  },
  rootLayerId: "01h79x1hkxcgfzpykc26fx0khs",
  newLayers: [],
  tags: [],
  stories: [
    {
      __typename: "Story",
      id: "01h79x1j0f3xptq3pzgnysk6dp",
      title: "Default",
      panelPosition: "LEFT",
      isBasicAuthActive: false,
      basicAuthUsername: "",
      basicAuthPassword: "",
      alias: "",
      publicTitle: "",
      publicDescription: "",
      publicImage: "",
      publicNoIndex: false,
      pages: [
        {
          __typename: "StoryPage",
          id: "01ha3yqjspksp134k3gzv3yxnk",
          title: "Page",
          swipeable: false,
          propertyId: "01ha3yqjspksp134k3gz04a9d2",
          property: {
            __typename: "Property",
            id: "01ha3yqjspksp134k3gz04a9d2",
            schema: {
              __typename: "PropertySchema",
              id: "reearth/storyPage",
              groups: [
                {
                  __typename: "PropertySchemaGroup",
                  schemaGroupId: "panel",
                  title: "Panel Setting",
                  translatedTitle: "Panel Setting",
                  isList: false,
                  representativeFieldId: null,
                  isAvailableIf: null,
                  fields: [
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "padding",
                      title: "Padding",
                      description: "",
                      translatedTitle: "Padding",
                      translatedDescription: "",
                      prefix: null,
                      suffix: null,
                      type: "SPACING",
                      defaultValue: null,
                      ui: "PADDING",
                      min: 0,
                      max: 100,
                      choices: null,
                      isAvailableIf: null,
                    },
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "gap",
                      title: "Gap",
                      description: "",
                      translatedTitle: "Gap",
                      translatedDescription: "",
                      prefix: null,
                      suffix: "px",
                      type: "NUMBER",
                      defaultValue: null,
                      ui: null,
                      min: null,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                  ],
                },
                {
                  __typename: "PropertySchemaGroup",
                  schemaGroupId: "title",
                  title: "Title Setting",
                  translatedTitle: "Title Setting",
                  isList: false,
                  representativeFieldId: null,
                  isAvailableIf: null,
                  fields: [
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "title",
                      title: "Title",
                      description: "",
                      translatedTitle: "Title",
                      translatedDescription: "",
                      prefix: null,
                      suffix: null,
                      type: "STRING",
                      defaultValue: null,
                      ui: null,
                      min: null,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "color",
                      title: "Color",
                      description: "",
                      translatedTitle: "Color",
                      translatedDescription: "",
                      prefix: null,
                      suffix: null,
                      type: "STRING",
                      defaultValue: null,
                      ui: "COLOR",
                      min: null,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                  ],
                },
                {
                  __typename: "PropertySchemaGroup",
                  schemaGroupId: "cameraAnimation",
                  title: "Camera Animation",
                  translatedTitle: "Camera Animation",
                  isList: false,
                  representativeFieldId: null,
                  isAvailableIf: null,
                  fields: [
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "cameraPosition",
                      title: "Camera position",
                      description: "",
                      translatedTitle: "Camera position",
                      translatedDescription: "",
                      prefix: null,
                      suffix: null,
                      type: "CAMERA",
                      defaultValue: null,
                      ui: null,
                      min: null,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "cameraDuration",
                      title: "Duration",
                      description: "",
                      translatedTitle: "Duration",
                      translatedDescription: "",
                      prefix: null,
                      suffix: "s",
                      type: "NUMBER",
                      defaultValue: null,
                      ui: null,
                      min: 0,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "cameraDelay",
                      title: "Delay",
                      description: "",
                      translatedTitle: "Delay",
                      translatedDescription: "",
                      prefix: null,
                      suffix: "s",
                      type: "NUMBER",
                      defaultValue: null,
                      ui: null,
                      min: 0,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                  ],
                },
                {
                  __typename: "PropertySchemaGroup",
                  schemaGroupId: "timePoint",
                  title: "Time Point Setting",
                  translatedTitle: "Time Point Setting",
                  isList: false,
                  representativeFieldId: null,
                  isAvailableIf: null,
                  fields: [
                    {
                      __typename: "PropertySchemaField",
                      fieldId: "timePoint",
                      title: "Time",
                      description: "",
                      translatedTitle: "Time",
                      translatedDescription: "",
                      prefix: null,
                      suffix: null,
                      type: "STRING",
                      defaultValue: null,
                      ui: "DATETIME",
                      min: null,
                      max: null,
                      choices: null,
                      isAvailableIf: null,
                    },
                  ],
                },
              ],
            },
            items: [],
          },
          blocks: [
            {
              __typename: "StoryBlock",
              id: "01ha3yr4jcmvxd59d15dw0td81",
              pluginId: "reearth",
              extensionId: "storyBlock",
              property: {
                __typename: "Property",
                id: "01ha3yr4jcmvxd59d15cpt672v",
                schema: {
                  __typename: "PropertySchema",
                  id: "reearth/storyBlock",
                  groups: [
                    {
                      __typename: "PropertySchemaGroup",
                      schemaGroupId: "default",
                      title: "Basic",
                      translatedTitle: "Basic",
                      isList: false,
                      representativeFieldId: null,
                      isAvailableIf: null,
                      fields: [
                        {
                          __typename: "PropertySchemaField",
                          fieldId: "title",
                          title: "Title",
                          description: "",
                          translatedTitle: "Title",
                          translatedDescription: "",
                          prefix: null,
                          suffix: null,
                          type: "STRING",
                          defaultValue: null,
                          ui: null,
                          min: null,
                          max: null,
                          choices: null,
                          isAvailableIf: null,
                        },
                      ],
                    },
                  ],
                },
                items: [],
              },
            },
          ],
        },
      ],
    },
  ],
  teamId: "01h6tpqrk5nxpckgfsw3h89p6x",
  widgetAlignSystem: {
    __typename: "WidgetAlignSystem",
    outer: {
      __typename: "WidgetZone",
      left: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
      center: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
      right: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
    },
    inner: {
      __typename: "WidgetZone",
      left: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
      center: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
      right: {
        __typename: "WidgetSection",
        top: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        middle: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
        bottom: {
          __typename: "WidgetArea",
          widgetIds: [],
          align: "START",
          padding: null,
          gap: null,
          centered: false,
          background: null,
        },
      },
    },
  },
  widgets: [],
};
