viz: Visualizer
map: Map
plugin: Plugins
mantle: mantle
engine: Engine
crust: Crust
infobox: Infobox
was: Widgets
cesium: Cesium
feature: Feature

viz -> crust: use
crust -> plugin: use
crust -> was: use
crust -> infobox: use
viz -> map: use
engine -> map: inject
engine -> mantle: use
engine -> cesium: use
cesium -> feature: use
map -> mantle: use
