name: ci-web
on:
  workflow_call:
jobs:
  validate-nginx-config:
    uses: reearth/actions/.github/workflows/validate-nginx-config.yml@4a7719ea2bfbcf3841b58eaedb01e91d3520227a
    with:
      template_directory: docker
      template_values: '{"PORT": 8080, "REAL_IP_HEADER": "X-Forwarded-For"}'
      working_directory: web
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install
      - name: type
        run: yarn run type
      - name: eslint
        run: yarn run lint
      - name: Check
        run: yarn run coverage
      - name: Send coverage report
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web,web-beta,web-classic,web-utils
      - name: Check translations
        run: yarn run i18n --fail-on-update
