name: cleanup-service-revision-pr
on:
  pull_request:
    types:
      - closed
permissions:
  contents: read
  id-token: write
jobs:
  show-github-event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "PR number: ${{ github.event.pull_request.number }}"

  cleanup-pr-revision-server:
    needs: [show-github-event-info]
    uses: ./.github/workflows/cleanup-cloudrun-tag.yml
    with:
      service: reearth-visualizer-api
      tag: pr-${{ github.event.pull_request.number }}
    secrets: inherit

  cleanup-pr-revision-web:
    needs: [show-github-event-info]
    uses: ./.github/workflows/cleanup-cloudrun-tag.yml
    with:
      service: reearth-visualizer-web
      tag: pr-${{ github.event.pull_request.number }}
    secrets: inherit
