name: cleanup-service-revision-pr
on:
  pull_request:
    types:
      - closed
permissions:
  contents: read
  id-token: write
jobs:
  show-github-event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Print event information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "PR number: ${{ github.event.pull_request.number }}"

  cleanup-pr-revision-api:
    needs: [show-github-event-info]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Remove Cloud Run Tag
        uses: reearth/actions/remove-cloud-run-tag@c8d4668fb6d90e6f877429e4c6421dfec8b39a91 # main
        with:
          region: ${{ secrets.GC_REGION }}
          service: reearth-visualizer-api
          service_account: ${{ secrets.GC_SA_EMAIL }}
          tag: pr-${{ github.event.pull_request.number }}
          workload_identity_provider: ${{ secrets.GC_WORKLOAD_IDENTITY_PROVIDER }}

  cleanup-pr-revision-web:
    needs: [show-github-event-info]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Remove Cloud Run Tag
        uses: reearth/actions/remove-cloud-run-tag@c8d4668fb6d90e6f877429e4c6421dfec8b39a91 # main
        with:
          region: ${{ secrets.GC_REGION }}
          service: reearth-visualizer-web
          service_account: ${{ secrets.GC_SA_EMAIL }}
          tag: pr-${{ github.event.pull_request.number }}
          workload_identity_provider: ${{ secrets.GC_WORKLOAD_IDENTITY_PROVIDER }}
