name: Dependency Review
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:

jobs:
  server-dependency-review:
    uses: reearth/actions/.github/workflows/go-dependency-check.yml@go-dependency-check
    with:
      subdirectory: server
