name: E2E-Playwright-Tests-Dev

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/e2e/playwright-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and Playwright browsers
        run: |
          npm ci
          
      - name: Install Playwright browsers
        run: npx playwright install

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.REEARTH_WEB_E2E_USERNAME }}" ]; then
            echo "Error: REEARTH_WEB_E2E_USERNAME secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.REEARTH_WEB_E2E_PASSWORD }}" ]; then
            echo "Error: REEARTH_WEB_E2E_PASSWORD secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.REEARTH_WEB_E2E_BASEURL }}" ]; then
            echo "Error: REEARTH_WEB_E2E_BASEURL secret is not set."
            exit 1
          fi

      - name: Run Playwright tests
        env:
          REEARTH_WEB_E2E_USERNAME: ${{ secrets.REEARTH_WEB_E2E_USERNAME }}
          REEARTH_WEB_E2E_PASSWORD: ${{ secrets.REEARTH_WEB_E2E_PASSWORD }}
          REEARTH_WEB_E2E_BASEURL: ${{ secrets.REEARTH_WEB_E2E_BASEURL }}
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: server/e2e/playwright-tests/playwright-report/
          retention-days: 30
