name: Verify Checklist Completion

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Get PR body
        id: pr
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            core.setOutput("body", body);

      - name: Validate checklist
        env:
          BODY: ${{ steps.pr.outputs.body }}
        run: |
          if echo "$BODY" | grep -q '\- \[ \]'; then
            echo "❌ There are unchecked items in the checklist on this PR."
            exit 1
          fi
          echo "✅ All checklist items are checked on this PR."
