name: renovate
on:
  push:
    branches:
      - renovate/*
jobs:
  renovate-go-sum-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@v0
        with:
          git_user: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_style: squash
          push: force
