name: Reviewer lottery
on:
  pull_request_target:
    paths:
        - web/**
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: uesteibar/reviewer-lottery@c291d74388da1cb583aff994b8be945e8eefbcd5 # v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
