name: Update Cesium Ion token Nightly

# Every 2nd day of the month at 02:00 JST.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 1 * *'
jobs:
  upload:
    uses: ./.github/workflows/_upload_cesium_token_txt.yml
    secrets:
      credentials_json: ${{ secrets.GCP_SA_KEY }}
      secret_name: ${{ secrets.CESIUM_ION_TOKEN_SECRET_NAME }}
